export class Sound{
 constructor(){this.ctx=null;this.volume=.4;this.lastBird=0;this.seen=new Set();}
 start(){if(this.ctx){this.ctx.resume();return;}this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=this.volume*.35;this.master.connect(this.ctx.destination);let buffer=this.ctx.createBuffer(1,this.ctx.sampleRate*3,this.ctx.sampleRate),d=buffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*.5;this.noise=buffer;let wind=this.ctx.createBufferSource();wind.buffer=buffer;wind.loop=true;let filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=330;let gain=this.ctx.createGain();gain.gain.value=.16;wind.connect(filter).connect(gain).connect(this.master);wind.start();}
 setVolume(v){this.volume=v;if(this.master)this.master.gain.value=v*.35;}
 tone(f,d=.15,type='sine',gain=.15,end=f){if(!this.ctx)return;let o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(1,end),t+d);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g).connect(this.master);o.start();o.stop(t+d);}
 rustle(d=.15,gain=.2,freq=700){if(!this.ctx)return;let s=this.ctx.createBufferSource(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter(),t=this.ctx.currentTime;s.buffer=this.noise;f.type='lowpass';f.frequency.value=freq;g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.001,t+d);s.connect(f).connect(g).connect(this.master);s.start();s.stop(t+d);}
 update(sim){if(!this.ctx)return;for(let e of sim.events){let k=e.type+':'+e.t;if(this.seen.has(k))continue;this.seen.add(k);if(e.type==='gather'||e.type==='craft')this.tone(480,.12,'sine',.08,750);else if(e.type==='throw')this.rustle(.2,.25,1900);else if(e.type==='impact'||e.type==='chop'){this.rustle(.14,.5,850);this.tone(130,.09,'triangle',.28,48);}else if(e.type==='hurt')this.tone(80,.18,'triangle',.2,40);else if(e.type==='drink')this.rustle(.5,.18,1600);else if(e.type==='animal')this.tone(120,.4,'sawtooth',.035,80);}
  if(this.seen.size>150)this.seen.clear();let now=this.ctx.currentTime;if(now-this.lastBird>4.2){this.lastBird=now;if(sim.phase==='Night')this.tone(2800,.15,'sine',.015,2900);else{this.tone(1700,.13,'sine',.035,2500);setTimeout(()=>this.tone(2200,.12,'sine',.025,1600),170);}}
  let p=sim.position,v=sim.player.linvel();if(sim.grounded&&Math.hypot(v.x,v.z)>1&&now-(this.lastStep||0)>.37){this.lastStep=now;this.rustle(.1,.11,450);}
 }
}
