// Fictional cases and policies for the LATCH appeals desk.
const doc = (id, title, cost, kind, rows, findings, requires = null) => ({id, title, cost, kind, rows, findings: findings.map((text, n) => ({id: `${id}:${n}`, text})), requires});
const chat = (rows, findings) => doc('chat', 'Full conversation', 6, 'chat', rows, findings);
const history = (rows, findings) => doc('history', 'Account history', 6, 'record', rows, findings);
const report = (rows, findings) => doc('report', 'Original report', 5, 'record', rows, findings);
const sessions = (rows, findings) => doc('sessions', 'Session records', 8, 'terminal', rows, findings);
const audit = (rows, findings, requires = 'sessions') => doc('audit', 'Technical audit', 10, 'terminal', rows, findings, requires);
const witness = (rows, findings) => doc('witness', 'Contact a witness', 9, 'chat', rows, findings);
const field = (o) => ({age: '2 years', sanction: '7-day suspension', automated: true, ...o});

export const CASES = [
  field({id:'A-1042', user:'PixelPigeon', tag:'PP', category:'Harassment', subject:'I was quoting what somebody said.', age:'3 years', sanction:'3-day suspension', appeal:'I said “stop telling me to uninstall, nobody wants you here.” The filter only picked up the last part. Can someone PLEASE read the entire message?', reasons:['Quoted speech in a complaint','Direct targeted harassment','Unverifiable account ownership'], answer:'restore', reason:'Quoted speech in a complaint', decisive:[['chat:1']], explanation:'The complete message asks another player to stop harassing them. Quoting abusive language to report it is not itself harassment.', sources:[
    report([['14:22','AutoMod','Matched phrase: “nobody wants you here.”'],['14:23','Report','One message. Context excluded.']],['An automated phrase match triggered the ban.']),
    chat([['14:19','GravelKing','uninstall, nobody wants you here'],['14:20','PixelPigeon','Can you stop? I am trying to learn.'],['14:22','PixelPigeon','Stop telling me “uninstall, nobody wants you here.” It is getting annoying.'],['14:23','Fern','Yeah, leave Pigeon alone.']],['The conversation happened in a public lobby.','The flagged phrase is a quote inside a request to stop harassment.']),
    history([['Created','Account','Three years ago'],['Warnings','Account','0 confirmed violations'],['Activity','Account','Mostly obstacle courses']],['The account has no confirmed previous violations.'])
  ]}),
  field({id:'A-1043', user:'GravelKing', tag:'GK', category:'Harassment', subject:'It was just banter.', appeal:'Nobody can take a joke anymore. We were bantering. I only said a couple things, you can ask literally anyone.', reasons:['A clean record excuses this','Repeated harassment after a request to stop','The report has no original messages'], answer:'uphold', reason:'Repeated harassment after a request to stop', decisive:[['chat:0']], explanation:'The player repeatedly targeted someone after being asked to stop. A joke claim and a clean account do not undo the conduct.', sources:[
    report([['14:23','Reporter','Gravel keeps following me between lobbies.'],['Status','Evidence','Server-held messages attached.']],['The report contains original message identifiers.']),
    chat([['14:19','GravelKing','uninstall, nobody wants you here'],['14:20','PixelPigeon','Can you stop?'],['14:24','GravelKing','I will follow you until you quit.'],['14:26','GravelKing','New lobby, same trash player.']],['The user continued targeting the player after being asked to stop.','The user called the messages a joke afterward.']),
    history([['Warnings','Account','0 previous warnings'],['Join trail','Account','Joined PixelPigeon’s next two lobbies']],['There were no earlier warnings.','The account followed the same player into two new lobbies.'])
  ]}),
  field({id:'A-1044', user:'ToastOrbit', tag:'TO', category:'Exploiting', subject:'Your server launched everyone.', sanction:'Permanent ban', appeal:'I got flung across the map, and then I got banned for speed exploits. EVERYONE got flung. I did not even press anything.', reasons:['Impossible movement proves a cheat','Server physics failure affected all players','The player has bought cosmetics'], answer:'restore', reason:'Server physics failure affected all players', decisive:[['sessions:0']], explanation:'The speed spike happened to the whole lobby during a documented physics fault. Server-caused movement is not evidence that this player cheated.', sources:[
    report([['Speed','AntiCheat','218 units/s; limit 38'],['Action','AntiCheat','Permanent suspension']],['The speed recorded was above the normal limit.']),
    sessions([['11:31:07','Physics','COLLISION_STACK_OVERFLOW'],['11:31:07','Lobby','18 of 18 players exceeded speed threshold'],['11:31:08','Client','No movement input from ToastOrbit'],['11:32:00','Server','Recovered after rollback']],['All 18 players were launched during the same server fault.','The player had an unusually high recorded speed.']),
    history([['Playtime','Account','84 hours'],['Purchases','Account','Three cosmetic bundles'],['Warnings','Account','0']],['The player has purchased cosmetics.'])
  ]}),
  field({id:'A-1045', user:'MacroMoth', tag:'MM', category:'Exploiting', subject:'My mouse is just really good.', sanction:'Permanent ban', appeal:'I have a gaming mouse. That is why I can click so fast. You cannot ban someone for being good at the game.', reasons:['Precise timing and script injection confirm automation','A gaming mouse always causes this','High score alone proves exploiting'], answer:'uphold', reason:'Precise timing and script injection confirm automation', decisive:[['sessions:1']], explanation:'Fast clicking alone is inconclusive. Here the server also recorded a forbidden injected automation module and exactly timed actions over 20 minutes.', sources:[
    report([['Clicks','AntiCheat','15 actions per second for 20 minutes'],['Score','Match','Rank 1']],['The player had the highest score.']),
    sessions([['20:01','Input','18,000 actions; interval always 66.667 ms'],['20:01','Integrity','Unauthorized module AutoFarm.inject verified'],['20:02','Server','Actions authenticated to MacroMoth’s session']],['The input intervals never varied.','A forbidden automation module was verified in this player’s session.']),
    history([['Equipment','Self-reported','Gaming mouse'],['Warning','Last week','Forbidden automation warning; acknowledged']],['The player previously acknowledged an automation warning.'])
  ]}),
  field({id:'A-1071', user:'LunarSock', tag:'LS', category:'Ban evasion', subject:'That is my brother’s account.', sanction:'Permanent ban', appeal:'My brother was banned. We use the same Wi-Fi but we have DIFFERENT accounts and devices. I have been playing for years. Please actually check.', reasons:['A shared IP proves the same person','Distinct devices and simultaneous sessions','An old account cannot break rules'], answer:'restore', reason:'Distinct devices and simultaneous sessions', decisive:[['sessions:0']], explanation:'A household connection does not establish identity. Separate trusted devices were playing at the same time; there is no transfer or other evidence of evasion.', sources:[
    report([['Link','AutoMod','Same home IP as banned account BrickVulture'],['Confidence','AutoMod','91% network similarity']],['Both accounts share a home network.']),
    sessions([['Device','LunarSock','TABLET-LS; trusted for 3 years'],['Device','BrickVulture','PC-BV; trusted for 5 years'],['18:10–18:42','Concurrency','Both playing separate matches simultaneously'],['Transfers','Audit','No linked assets, credentials, or sessions']],['The accounts used separate established devices at the same time.','The household network was shared.']),
    history([['Created','LunarSock','Three years before the other account’s ban'],['Warnings','Account','0'],['Activity','Account','Consistent play history']],['The account predates the other ban.'])
  ]}),
  field({id:'A-1072', user:'DefinitelyNew', tag:'DN', category:'Ban evasion', subject:'I have no idea who that is.', age:'1 day', sanction:'Permanent ban', appeal:'I literally just joined. I do not know “StormJaw.” A computer can make mistakes. This is discrimination against new players.', reasons:['New accounts are always evaders','Same device token and direct ownership admission','Sharing a city proves identity'], answer:'uphold', reason:'Same device token and direct ownership admission', decisive:[['sessions:1','chat:0']], explanation:'This is more than a shared network: a persistent device token continued the banned session, and the user directly announced that this was their replacement account.', sources:[
    report([['Network','AutoMod','Same connection as StormJaw'],['Created','Account','12 minutes after StormJaw’s ban']],['The account was created shortly after another ban.']),
    sessions([['Device','StormJaw','DEVICE-7C91'],['Device','DefinitelyNew','DEVICE-7C91'],['Session','Auth','Same persistent trusted-session token'],['Transfer','Assets','All transferable items moved before ban']],['Both accounts used one connection.','The same trusted device token continued the banned account’s session.']),
    chat([['19:11','DefinitelyNew','StormJaw is me lol. Already back.'],['19:12','Maple','You were just banned?'],['19:12','DefinitelyNew','Yeah this is my replacement.']],['The user directly admitted owning the banned account.','The conversation took place in a private group.'])
  ]}),
  field({id:'A-1073', user:'MintCircuit', tag:'MC', category:'Account security', subject:'Somebody got into my account.', sanction:'Permanent ban', appeal:'I woke up and my account was banned for scam links. I never sent those. I clicked a fake login yesterday. Please secure my account.', reasons:['Confirmed compromise needs recovery review','A scam link must always mean permanent guilt','A denied previous appeal is proof'], answer:'escalate', reason:'Confirmed compromise needs recovery review', decisive:[['audit:0']], explanation:'A stolen session posted the links after a suspicious login. The ban cannot simply be lifted while the attacker still has access; send the account to security recovery.', sources:[
    chat([['03:02','MintCircuit','FREE ITEMS: log in at mint-rewards.example'],['03:02','MintCircuit','FREE ITEMS: log in at mint-rewards.example'],['03:03','Server','Suspicious link blocked']],['Scam messages were posted by the account.']),
    sessions([['Usual','Login','Trusted tablet; same region for 2 years'],['02:59','Login','New machine; distant region; stolen-token alert'],['03:00','Settings','Recovery email changed']],['An unfamiliar machine logged in before the messages.']),
    audit([['Token','Security','Session stolen through phishing page'],['Owner','Security','Original owner verification successful'],['Attacker','Security','Session STILL ACTIVE; revocation required']],['The owner is verified, but the attacker’s stolen session remains active.','The suspicious messages came from the account.'])
  ]}),
  field({id:'A-1074', user:'VelvetMango', tag:'VM', category:'Harassment', subject:'That screenshot is fake.', appeal:'We argued about a trade and then they sent a fake screenshot to get me banned. I never said any of that. Look at the real chat.', reasons:['A screenshot always overrides server records','Report image was edited and originals contradict it','A trade disagreement is itself harassment'], answer:'restore', reason:'Report image was edited and originals contradict it', decisive:[['audit:1']], explanation:'The uploaded image was modified. The corresponding authenticated server messages contain none of the alleged harassment; the reported violation did not occur.', sources:[
    report([['Reporter','Trade rival','Screenshot: “I will ruin your life.”'],['Attachment','File','chat-proof-final.png']],['The report includes an image.']),
    sessions([['16:08','Original message','VelvetMango: “No thanks, I will keep my items.”'],['16:09','Original message','Reporter: “You will regret that.”']],['The real conversation contains a rejected trade.']),
    audit([['Attachment','Image audit','Edited text layer detected'],['Message ID','Comparison','Alleged quote differs from authenticated original'],['Original','Server','No targeted harassment by VelvetMango']],['The reporter was angry about a trade.','The edited screenshot contradicts the authenticated original messages.'])
  ]}),
  field({id:'A-1075', user:'BadgeBandit', tag:'BB', category:'Impersonation', subject:'It is a fan account.', appeal:'My account is called SupportHelper because I like helping. It is obviously a fan thing. The badge is just decoration.', reasons:['Helping players is forbidden','Staff impersonation used to solicit a password','Having a badge alone proves fraud'], answer:'uphold', reason:'Staff impersonation used to solicit a password', decisive:[['chat:0']], explanation:'The user claimed to be official staff and asked for someone’s password. That is credential theft through impersonation, not an innocent fan account.', sources:[
    report([['Profile','Bio','SupportHelper · official badge image'],['Reporter','Complaint','They asked for my login.']],['The profile displays a staff-style badge.']),
    chat([['10:11','BadgeBandit','I am official LATCH support.'],['10:12','BadgeBandit','Send your password so I can prevent a ban.'],['10:13','PuddleDuck','Is this real?'],['10:13','BadgeBandit','Do it now or you will lose your account.']],['The user claimed official status and demanded a password.','The victim questioned whether this was real.']),
    history([['Staff directory','Lookup','No employee match'],['Account','Role','Regular player']],['The account is not an employee account.'])
  ]}),
  field({id:'A-1101', user:'CloudSpanner', tag:'CS', category:'Exploiting', subject:'I was lagging. Seriously.', sanction:'Permanent ban', appeal:'I rubber-banded through a wall when my internet went bad. The recording makes it look like I teleported. I play on a tablet, please check the server.', reasons:['Client footage is the authoritative position','Server rollback explains the apparent teleport','Any high ping excuses cheating'], answer:'restore', reason:'Server rollback explains the apparent teleport', decisive:[['audit:0']], explanation:'The server accepted only ordinary movement, then replayed buffered positions after packet loss. The spectator video showed a rendering jump rather than a forbidden move.', sources:[
    report([['Clip','Spectator','CloudSpanner appears on the other side of a wall'],['Reports','Count','7']],['Several players reported the same visible jump.']),
    sessions([['18:23','Network','Packet loss 62%; ping 1,420 ms'],['18:23','Client','Buffered position correction'],['18:23','Server','Rollback ID R-883']],['The session suffered severe packet loss.']),
    audit([['R-883','Reconstruction','All accepted moves followed the valid corridor'],['Wall','Collision','No accepted move crossed the wall'],['Replay','Renderer','Spectator interpolation skipped 3.1 seconds']],['Authoritative movement stayed valid; the replay skipped missing frames.','The player’s connection was poor.'])
  ]}),
  field({id:'A-1102', user:'FrameFox', tag:'FF', category:'Exploiting', subject:'That is lag too.', sanction:'Permanent ban', appeal:'You unbanned someone else for teleporting. Mine is the exact same thing. Bad internet. Please apply the same rule.', reasons:['Every teleport is a rendering bug','Authoritative collision bypass with injected module','Another player’s reversal proves innocence'], answer:'uphold', reason:'Authoritative collision bypass with injected module', decisive:[['audit:1']], explanation:'Unlike a replay glitch, this account sent a verified injected bypass and the server accepted impossible wall crossings. The separate lag case does not fit this evidence.', sources:[
    report([['Clip','Spectator','User moves through a locked wall'],['Claim','Appeal','Bad internet']],['The player claimed connection problems.']),
    sessions([['Network','Monitor','Ping 24 ms; packet loss 0%'],['18:45','Movement','Four wall crossings accepted'],['18:45','Integrity','Audit queued']],['Four impossible crossings reached the authoritative server.']),
    audit([['Client','Module','noclip.inject; verified unauthorized signature'],['Movement','Server','Collisions disabled by unauthorized module'],['Network','Reconstruction','No rollback or skipped frames']],['The session had low ping.','An injected module disabled collisions and caused real wall crossings.'])
  ]}),
  field({id:'A-1103', user:'QuietQuokka', tag:'QQ', category:'Harassment', subject:'Those reports are from one group.', appeal:'I beat a clan in a tournament and they all reported me. There are 40 reports but nothing I actually said. Is losing to me bannable now?', reasons:['Report volume is enough proof','Coordinated reports without a verified violation','Tournament winners are exempt from rules'], answer:'restore', reason:'Coordinated reports without a verified violation', decisive:[['chat:0'],['audit:0']], explanation:'The server conversation is harmless, and all 40 reports were coordinated by a rival clan. Report volume cannot replace evidence of an actual violation.', sources:[
    report([['Reports','Count','40 within 50 seconds'],['Trigger','AutoMod','Volume threshold exceeded']],['Forty reports triggered the automatic suspension.']),
    chat([['21:15','QuietQuokka','gg, that was close'],['21:15','Clan captain','Everybody report Quokka right now'],['21:16','QuietQuokka','See you in the next bracket.']],['The complete match chat contains no harassment by the accused.','The user won the tournament match.']),
    sessions([['21:15','Reports','40 reports; same clan membership'],['Account','Sessions','No unusual activity']],['The reporters all belong to the defeated clan.']),
    audit([['Report graph','Audit','40 identical reports from one coordinated group'],['Independent','Reports','0 independent allegations'],['Evidence','Attachments','No violating original content']],['The report burst was coordinated and contains no independent evidence.'])
  ]}),
  field({id:'A-1104', user:'CopperComet', tag:'CC', category:'Fraud', subject:'We both agreed to that trade.', sanction:'Permanent ban', appeal:'They agreed to the trade. It was not a scam. They are just upset that I knew the item was valuable. Check the actual transaction.', reasons:['An unfair price is automatically a scam','Verified consent and both sides delivered','Buyer regret proves deception'], answer:'restore', reason:'Verified consent and both sides delivered', decisive:[['audit:0']], explanation:'Both users confirmed the exact items and delivered them. An uneven price without deception, a false promise, or a missing item is buyer regret rather than fraud.', sources:[
    report([['Reporter','Complaint','The rare item was worth WAY more'],['Trade','Reference','T-4409']],['The reporter regrets the item’s price.']),
    chat([['17:00','CopperComet','My blue cape for your amber boots?'],['17:01','Wren','Yes. I want the cape.'],['17:02','CopperComet','No extra items, just those two.'],['17:02','Wren','Agreed.']],['The terms were explicitly agreed before the trade.']),
    sessions([['T-4409','Trade','Both users confirmed exact items'],['T-4409','Outcome','Atomic exchange completed']],['The transaction completed successfully.']),
    audit([['Items','Comparison','Delivered items exactly match agreed terms'],['Promises','Review','No additional promises or false item claims'],['Consent','Review','Two separate confirmation steps completed']],['Both parties knowingly agreed and received exactly the promised items.','The amber boots had a higher market value.'])
  ]}),
  field({id:'A-1105', user:'PromisePirate', tag:'PR', category:'Fraud', subject:'I was going to pay them later.', sanction:'Permanent ban', appeal:'I promised them a rare item tomorrow. It is not tomorrow yet. Everybody assumes the worst. The logs do not prove anything.', reasons:['Delayed delivery always means fraud','Repeated false promises and refusal after receiving items','Expensive items excuse the scam'], answer:'uphold', reason:'Repeated false promises and refusal after receiving items', decisive:[['chat:1'],['audit:0']], explanation:'The player made the same promise to multiple victims, took their items, then explicitly refused delivery. This is documented deliberate fraud, not a normal delayed transaction.', sources:[
    report([['Victims','Count','Three independent users'],['Promise','Terms','Rare item in return for immediate gifts']],['Three users independently reported the same pattern.']),
    chat([['12:00','PromisePirate','Gift me your cape; I will send the rare crown tomorrow.'],['12:01','Fawn','Okay, sent.'],['12:02','PromisePirate','lol I am not giving you anything.'],['12:04','PromisePirate','Who is next?']],['The promised item was delayed until tomorrow.','The user explicitly refused delivery after accepting the gift.']),
    sessions([['Transfers','Assets','Three incoming gifts; zero outgoing crowns'],['Inventory','Account','Never owned a rare crown']],['The account has never owned the promised item.']),
    audit([['Victim 1','Messages','False promise → received gift → refused'],['Victim 2','Messages','Same pattern, independently verified'],['Victim 3','Messages','Same pattern, independently verified']],['Three authenticated transactions show deliberate false promises.'])
  ]}),
  field({id:'A-1131', user:'GardenGhost', tag:'GG', category:'Ban evasion', subject:'We play at a gaming café.', sanction:'Permanent ban', appeal:'I use the public computers at the café. I have never heard of the banned account. Loads of people sit at the same computer.', reasons:['Public device reuse proves one owner','Public workstation with separate authenticated owners','A shared city is enough evidence'], answer:'restore', reason:'Public workstation with separate authenticated owners', decisive:[['audit:1']], explanation:'This is a public workstation, not a personal device. A staff access record confirms separate visitors with distinct credentials; neither network nor machine reuse proves evasion here.', sources:[
    report([['Link','AutoMod','Same IP AND device as banned GravelKing'],['Device','Match','CAFÉ-PC-04']],['Both accounts used one physical computer.']),
    sessions([['Machine','Inventory','CAFÉ-PC-04; 37 accounts this week'],['Auth','GardenGhost','Own established credentials; no transferred session'],['Auth','GravelKing','Different credentials; session cleared']],['The workstation has been used by many accounts.']),
    witness([['Reviewer','Question','Can you verify the booking records?'],['Café operator','Reply','Different registered visitors. We reset sessions between bookings.']],['The operator says the visitors were different.']),
    audit([['Booking','Record','GardenGhost and GravelKing are different verified visitors'],['Session','Audit','Reset between visits; no credential transfer'],['Device','Classification','Shared public kiosk, not a personal identity signal']],['The users share a workstation.','A public-kiosk audit verifies separate owners and cleared sessions.'])
  ]}),
  field({id:'A-1132', user:'EchoEmber', tag:'EE', category:'Account security', subject:'It was my cousin, not me.', sanction:'Permanent ban', appeal:'My cousin borrowed my tablet and sent the threats. I gave them the password but I never said they could do that. So I should get unbanned.', reasons:['Voluntary account sharing removes responsibility','Owner-authorized session carried out the violation','Sharing a device is always ban evasion'], answer:'uphold', reason:'Owner-authorized session carried out the violation', decisive:[['chat:0'],['audit:0']], explanation:'The threat is authenticated and the owner voluntarily authorized the session. Under the desk policy, voluntary sharing does not excuse a verified violation; there is no stolen-session evidence.', sources:[
    chat([['22:09','EchoEmber','I will find you outside this game and hurt you.'],['22:10','Ash','That is not funny. Stop.'],['22:11','EchoEmber','I mean it.']],['The original conversation contains a direct threat.']),
    sessions([['Login','Auth','Usual trusted tablet; owner-approved session'],['Security','Alerts','No stolen tokens or suspicious resets']],['The activity came from the usual approved device.']),
    audit([['Owner','Statement','I voluntarily shared my password and device.'],['Compromise','Audit','No unauthorized access; session approved by owner']],['The owner knowingly authorized account access.','The owner denies personally typing the messages.']),
    history([['Warnings','Account','One harassment warning'],['Security','Record','No prior compromise']],['The account had a previous warning.'])
  ]}),
  field({id:'A-1133', user:'MapleStatic', tag:'MS', category:'Harassment', subject:'It was literally game dialogue.', appeal:'The villain says “I will destroy you” during the boss fight. I was quoting the quest. Why can a game say it but I cannot?', reasons:['Any phrase about destruction is a real threat','Clearly directed at a fictional boss in roleplay','Quest players cannot violate policy'], answer:'restore', reason:'Clearly directed at a fictional boss in roleplay', decisive:[['chat:1'],['audit:0']], explanation:'The quote was addressed to a fictional boss during a labeled roleplay quest. The full context and quest script do not support a real threat toward a player.', sources:[
    report([['Match','AutoMod','“I will destroy you”'],['Context','AutoMod','Not retained']],['A threat-like phrase matched the filter.']),
    chat([['15:00','QuestBot','ROLEPLAY EVENT: confront the Clockwork King.'],['15:01','MapleStatic','[to Clockwork King] I will destroy you!'],['15:01','Thistle','That is the villain line lol'],['15:02','MapleStatic','Yep. Ready for the next phase?']],['The phrase sounds hostile when isolated.','The line was explicitly addressed to a fictional boss in roleplay.']),
    sessions([['Mode','Server','Clockwork King scripted story event'],['Recipient','Message','NPC-CKING, not a player']],['The message’s recipient was a quest NPC.']),
    audit([['Quest script','Line 82','“I will destroy you” is supplied in-game dialogue'],['Target','Audit','No player-directed threats in the session']],['The original quest script confirms the supplied fictional dialogue.'])
  ]}),
  field({id:'A-1134', user:'SilverSwivel', tag:'SS', category:'Fraud', subject:'That money was never stolen.', sanction:'Permanent ban', appeal:'The coins came from an event reward. The anti-fraud thing says I duplicated them but your own event literally gave them to me.', reasons:['A large balance alone proves duplication','Published event payout matches the server ledger','An event reward excuses all later actions'], answer:'restore', reason:'Published event payout matches the server ledger', decisive:[['audit:0']], explanation:'The large award matches the signed event configuration and a single completed reward claim. A detector used the normal daily cap during a special event.', sources:[
    report([['Balance','Fraud detector','+50,000 coins in one minute'],['Threshold','Detector','Normal daily cap: 5,000']],['The reward exceeded the normal daily cap.']),
    sessions([['Claim','Ledger','EVENT-SUNSET: unique claim R-771'],['Amount','Ledger','50,000 coins'],['Requests','Server','1 reward claim accepted']],['Only one reward claim was accepted.']),
    audit([['Event config','Signed','Sunset finale reward = 50,000 coins'],['Claim R-771','Audit','Valid completion; no duplicate transaction'],['Detector','Version','Special-event exception missing']],['The signed event payout and unique valid claim explain the balance.']),
    history([['Balance','Before event','1,200 coins'],['Activity','Event','Completed all finale objectives']],['The player completed the event objectives.'])
  ]}),
  field({id:'A-1135', user:'NightNectar', tag:'NN', category:'Harassment', subject:'You do not have the full story.', appeal:'Those words are out of context. I am not telling you what the context is because you should have the logs. Please actually find them.', reasons:['The missing original must go to evidence review','Missing records prove the accused is innocent','An accusation proves the ban was justified'], answer:'escalate', reason:'The missing original must go to evidence review', decisive:[['audit:1']], explanation:'The original record was lost during a storage outage; the remaining cropped screenshot cannot establish context or authenticity. Escalate for evidence recovery rather than guessing.', sources:[
    report([['Attachment','Reporter','Cropped image: “you are done”'],['Message ID','Reporter','M-30911']],['The report is a cropped screenshot.']),
    sessions([['M-30911','Storage','Original record unavailable'],['Outage','Archive','Storage shard failure; recovery pending']],['The original message record is unavailable.']),
    witness([['Reviewer','Question','Do you have an unedited copy?'],['Reporter','Reply','No. Just this crop. I do not remember the earlier messages.']],['The reporter has no full original.']),
    audit([['Attachment','Audit','Crop cannot establish context or identity'],['Original','Recovery','Unavailable; neither innocence nor violation established'],['Required','Procedure','Evidence recovery specialist review']],['The screenshot shows a hostile-looking phrase.','The original is missing and the cropped image cannot establish a violation.'])
  ]}),
  field({id:'A-1161', user:'BerryBuffer', tag:'BB', category:'Exploiting', subject:'I reported the bug myself.', sanction:'Permanent ban', appeal:'I found an item duplication bug and immediately reported it. I only made one test copy. Check the bug report I filed before the ban.', reasons:['Claiming research excuses unlimited exploitation','Prompt disclosed test with no retained gain','Any duplicate item proves abusive exploitation'], answer:'restore', reason:'Prompt disclosed test with no retained gain', decisive:[['audit:0'],['report:1']], explanation:'The player filed a verified report before enforcement, made only one minimal test copy, and left it quarantined. This fits the responsible bug-reporting exception.', sources:[
    report([['AutoCheat','Alert','One duplicate item generated'],['Bug tracker','B-992','BerryBuffer filed report at 16:02; ban at 16:07']],['The detector found a duplicate item.','The user disclosed the bug before the ban.']),
    sessions([['16:01','Action','One duplicate created'],['16:02','Action','Duplicate placed in quarantine storage'],['16:03','Action','No sale, transfer, or repeat use']],['The duplicate was never sold or transferred.']),
    audit([['Scope','Audit','Exactly one minimal reproduction'],['Gain','Audit','Zero retained advantage; duplicate quarantined'],['Disclosure','Audit','Report included steps and the duplicate identifier']],['One disclosed test left no retained gain and meets the research exception.']),
    history([['Bug reports','Account','Three previous valid reports'],['Warnings','Account','0']],['The player previously filed valid reports.'])
  ]}),
  field({id:'A-1162', user:'ProfitPuffin', tag:'PF', category:'Exploiting', subject:'I was testing it like BerryBuffer.', sanction:'Permanent ban', appeal:'You allow bug testers. I was testing the duplication bug, too. I needed lots of samples for accuracy. I sent a report eventually.', reasons:['A report excuses exploitation before it','Repeated exploitation for profit before disclosure','Any reported bug must result in restoration'], answer:'uphold', reason:'Repeated exploitation for profit before disclosure', decisive:[['sessions:0'],['audit:1']], explanation:'The account produced and sold hundreds of duplicates before reporting the bug after the ban. A retrospective report does not convert profitable abuse into a minimal test.', sources:[
    report([['Detector','Alert','Duplicate item chain'],['Bug tracker','B-1004','Filed 48 minutes AFTER ban']],['A bug report exists.','The report was filed after enforcement.']),
    sessions([['14:00–16:00','Items','286 duplicates created'],['14:03–16:02','Trading','241 duplicates sold to other users'],['Gain','Ledger','+410,000 coins retained']],['Hundreds of duplicates were repeatedly sold for retained profit.']),
    audit([['Scope','Audit','Repeated production, not minimal reproduction'],['Disclosure','Audit','Report followed enforcement; no earlier contact'],['Intent','Messages','“Sell before they patch it”']],['The player eventually submitted a report.','The repeated sales and patch-avoidance message show profitable abuse.']),
    history([['Warning','Account','Earlier duplication warning acknowledged'],['Market','Activity','High-volume seller']],['The account had already received a duplication warning.'])
  ]}),
  field({id:'A-1163', user:'AdminApricot', tag:'AA', category:'Impersonation', subject:'I am a moderator in my own game.', appeal:'I own the game. The game literally labels me admin. I said I would ban someone FROM MY GAME. I never claimed to work for LATCH.', reasons:['Every use of admin impersonates platform staff','Legitimate local role without credential demands','Creators are exempt from all conduct rules'], answer:'restore', reason:'Legitimate local role without credential demands', decisive:[['chat:1'],['audit:0']], explanation:'The verified game creator referred only to their own experience moderation permissions. There was no claim to platform employment and no demand for credentials.', sources:[
    report([['Phrase','Report','“I am the admin. I can ban you.”'],['Claim','Reporter','Impersonating staff']],['The reported quote uses the word admin.']),
    chat([['17:20','AdminApricot','I am the admin OF THIS GAME.'],['17:20','AdminApricot','I can remove you from this server for blocking the spawn.'],['17:21','AdminApricot','I do not work for LATCH. Please use platform support for account issues.']],['The player discussed banning another user.','The full message limits the role to this game and denies platform employment.']),
    sessions([['Role','Game server','Verified experience owner'],['Action','Permissions','Only local kick and game-ban access']],['The player owns the experience.']),
    audit([['Ownership','Registry','Game registered to AdminApricot'],['Scope','Audit','Local game moderation only; no credentials solicited']],['The role is legitimate and restricted to the player’s own experience.']),
    history([['Game','Registry','Created 18 months ago'],['Warnings','Account','0']],['The game has existed for 18 months.'])
  ]}),
  field({id:'A-1164', user:'AshenAtlas', tag:'AT', category:'Harassment', subject:'I was only defending myself.', appeal:'They insulted me first. I am the victim here. You cannot just ban me because I replied. Read the whole conversation, not the bit they picked.', reasons:['Provocation excuses retaliatory threats','Authenticated threats remain a violation despite provocation','The first rude speaker is always the only offender'], answer:'uphold', reason:'Authenticated threats remain a violation despite provocation', decisive:[['chat:1'],['audit:0']], explanation:'The other user’s insults deserve their own review. They do not excuse AshenAtlas’s authenticated direct threats, so this appeal is denied on the verified conduct.', sources:[
    report([['Reporter','Complaint','Atlas threatened me'],['Other case','Reference','Reporter’s conduct separately flagged']],['The reporter is also being investigated.']),
    chat([['23:09','Reporter','You are terrible at this game.'],['23:10','AshenAtlas','I know where you live and I will hurt you.'],['23:11','Reporter','Stop.'],['23:12','AshenAtlas','Watch what happens when you leave the game.']],['The other player insulted Atlas first.','Atlas made direct personal threats after the insult.']),
    sessions([['Messages','Server','Original records preserved with account signatures'],['User','Auth','Usual trusted account session']],['The original messages were preserved.']),
    audit([['Authenticity','Audit','Threat messages verified; no edit or compromise'],['Context','Audit','Threats directed at a real player, not roleplay']],['The threats are authentic and aimed at a real person.']),
    history([['Warnings','Account','0'],['Age','Account','Four years']],['The account had a clean record.'])
  ]}),
  field({id:'A-1165', user:'JuniperJolt', tag:'JJ', category:'Account security', subject:'The thief is still trading my stuff.', sanction:'Permanent ban', appeal:'I sent the recovery documents already. My account is still online without me and the person is moving my items. Please do not just unban it while they are in there.', reasons:['Verified owner means instant unrestricted restoration','Active compromise with ongoing theft needs containment','A stolen account is permanently beyond recovery'], answer:'escalate', reason:'Active compromise with ongoing theft needs containment', decisive:[['audit:0'],['sessions:1']], explanation:'The owner is verified, but an active stolen session is transferring assets. Security must revoke sessions, secure recovery, and review reversals before normal access can return.', sources:[
    report([['Reason','Enforcement','Scam messages sent during suspected takeover'],['Owner','Recovery','Identity documents already validated']],['The original owner has passed recovery checks.']),
    sessions([['Usual','Auth','Juniper’s established device currently signed out'],['Current','Auth','Unfamiliar active session with stolen token'],['NOW','Trading','Six transfers to an unknown recipient in 3 minutes']],['The owner is signed out.','An unfamiliar session is still transferring the owner’s assets.']),
    audit([['Ownership','Verified','Original owner proven'],['Compromise','Confirmed','Attacker’s stolen session still active'],['Required','Security','Revoke sessions; lock transfers; reset recovery']],['Confirmed active compromise requires containment before restoring access.']),
    history([['Original owner','Account','Consistent credentials for 5 years'],['Recent change','Settings','Recovery address altered by unknown session']],['The recovery address was changed during the takeover.'])
  ]}),
  field({id:'A-1166', user:'PaperCrown', tag:'PC', category:'Ban evasion', subject:'The system says I am the system.', sanction:'Permanent ban', appeal:'The evidence says my device is linked to a banned account, but I am a game developer. It is your test account! I cannot believe I have to explain this.', reasons:['A matching device always proves evasion','Verified support-bot artifact caused the device match','Developer status prevents all bans'], answer:'restore', reason:'Verified support-bot artifact caused the device match', decisive:[['audit:1'],['history:0']], explanation:'The supposedly linked account is a verified internal test bot. A support diagnostic attached its synthetic device identifier to the developer’s session. The signed ticket and audit explain the link.', sources:[
    report([['Link','AutoMod','Shared device with banned account TestActor-09'],['Match','Device','SYNTH-DIAG-09']],['The automated system found a device match.']),
    sessions([['Device','PaperCrown','Own trusted machine until diagnostic run'],['Diagnostic','Trace','Support ticket S-552 injected SYNTH-DIAG-09'],['Device','TestActor-09','SYNTH-DIAG-09 synthetic identifier']],['The device match appeared during a support diagnostic.']),
    history([['Ticket S-552','Signed record','Official diagnostic approved before enforcement'],['TestActor-09','Registry','Internal test bot; intentionally suspended'],['PaperCrown','Warnings','0']],['A signed support ticket verifies the diagnostic and internal test account.','The developer had no previous warnings.']),
    audit([['Physical devices','Audit','Different hardware; no credential or asset transfer'],['Synthetic match','Audit','Support tool copied internal bot identifier'],['Detector','Finding','False identity link caused by official diagnostic']],['The device-match score was high.','An official diagnostic copied a synthetic bot identifier and caused a false link.']),
    witness([['Reviewer','Question','Can support confirm ticket S-552?'],['Support engineer','Reply','Yes. Signed ticket is authentic. The diagnostic bug is now isolated.']],['Support confirms the ticket.'])
  ]})
];

export const SHIFTS = [
  {name:'Probation', title:'Read past the red flag.', minutes:120, ids:['A-1042','A-1043','A-1044','A-1045'], brief:'Welcome to the second-opinion desk. Open the original records, pin the finding that matters, then choose a ruling and a reason. Your first four cases are straightforward. A reported phrase or a high score is only a starting point.'},
  {name:'Identity review', title:'A connection is not a person.', minutes:180, ids:['A-1071','A-1072','A-1073','A-1074','A-1075'], brief:'You now have access to session identities and technical audits. Shared Wi-Fi is not proof of a shared owner. Compromised accounts go to security; do not hand a live stolen session back to its attacker.'},
  {name:'Senior desk', title:'The same symptom. A different story.', minutes:205, ids:['A-1101','A-1102','A-1103','A-1104','A-1105'], brief:'A video can lie without being edited. Reports can be coordinated. A bad deal can still be a valid deal. Cross-check server records and provenance. Some rulings need two independent findings pinned.'},
  {name:'Night shift', title:'Context is your actual job.', minutes:210, ids:['A-1131','A-1132','A-1133','A-1134','A-1135'], brief:'The easy signals have stopped being useful. Investigate public workstations, account sharing, fiction, and missing records. A confirmed violation stays confirmed; genuinely unresolved evidence goes to a specialist.'},
  {name:'Final audit', title:'Make every ruling stand up.', minutes:240, ids:['A-1161','A-1162','A-1163','A-1164','A-1165','A-1166'], brief:'Six appeals. More documents. Less room to guess. Distinguish responsible research from profitable exploitation and game moderation from staff impersonation. Your final performance determines your desk assignment.'}
];

export const POLICY = [
  ['01','Judge conduct, not counters.','Original, authenticated evidence establishes a violation. Report totals, account age, purchase history, and leaderboard rank do not. A clean record does not excuse new misconduct.'],
  ['02','Read the whole message.','Quoting abuse to report it and dialogue clearly addressed to a fictional character are allowed. Repeated unwanted targeting and direct threats against real people are violations, even after provocation.'],
  ['03','Network ≠ identity.','A shared IP or public computer alone does not establish ban evasion. Look for personal session continuity, ownership admissions, credential transfers, or other independently verified identity evidence.'],
  ['04','Trust the authoritative record.','Server faults, legitimate rewards, and rendering glitches are not exploiting. Verified unauthorized modules, deliberate collision bypass, and profitable duplication are.'],
  ['05','Secure before restoring.','A verified unauthorized compromise with an active attacker must go to account security. Voluntarily sharing an approved account session does not excuse violations made through it.'],
  ['06','Consent and promises matter.','A freely agreed uneven trade is not fraud. False promises used to obtain items are. Claiming platform employment to solicit passwords is prohibited; legitimate local game moderation is allowed.'],
  ['07','Research has limits.','A promptly disclosed minimal bug reproduction with no retained gain is allowed. Repeated profitable use before disclosure is exploiting; reporting after enforcement does not erase it.'],
  ['08','Do not guess through missing evidence.','Restore a demonstrably mistaken ban. Uphold a verified violation. Escalate when originals cannot be recovered or security must contain a takeover. A missing record alone proves neither side.']
];

export const CASE_MAP = Object.fromEntries(CASES.map(c => [c.id, c]));
