import * as T from './vendor/three.js';
import {World,ROOMS,BOT_TYPES,dist,clamp,roomAt,sector} from './world.js';
import {WorldView,handsModel,buildModel} from './models.js';
import {Simulation} from './sim.js';
import {Session} from './network.js';
import {Sound} from './audio.js';
const $=id=>document.getElementById(id),show=id=>$(id).classList.remove('hidden'),hide=id=>$(id).classList.add('hidden');
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const saved=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
let settings={quality:'balanced',sensitivity:1,volume:.45,voice:false,motion:matchMedia('(prefers-reduced-motion: reduce)').matches,touch:matchMedia('(pointer:coarse)').matches,...saved('still-here-settings',{})};
let best=saved('still-here-record',{time:0,days:0,secrets:0}),selectedBots=new Set(['mira','dex','sol']);
let renderer,scene,camera,view,world,hemi,ambient,sun,flash,flashTarget,nearLights=[],hands,ghost,lightLevel=1;
let sim=null,state=null,session=null,localId='solo',mode='menu',modal=null,settingsReturn=null,input={mx:0,mz:0,yaw:0,pitch:0,sprint:false,jump:false};
let keys=new Set(),touchMove={x:0,y:0},touchSprint=false,touchJump=false,buildMode=false,buildKind='wall',buildRot=0,buildPosition=null;
let lastNow=performance.now(),accumulator=0,netAcc=0,hudAcc=0,lastMessage=0,lastEvent=0,lastHp=100,lastPhase=false,bob=0,prediction=null;
let toastTimer,eventTimer,damageTimer;const sound=new Sound();let cachedChat='',lastDiscovery=-1;
function toast(text){$('toast').textContent=text;show('toast');clearTimeout(toastTimer);toastTimer=setTimeout(()=>hide('toast'),3500)}
function banner(kicker,title){$('event-kicker').textContent=kicker;$('event-title').textContent=title;show('event-banner');clearTimeout(eventTimer);eventTimer=setTimeout(()=>hide('event-banner'),5000)}
function renderBotChoices(){const div=$('bot-options');div.innerHTML='';for(const b of BOT_TYPES){const btn=document.createElement('button');btn.className='bot-option'+(selectedBots.has(b.id)?' selected':'');btn.setAttribute('aria-pressed',String(selectedBots.has(b.id)));btn.setAttribute('aria-label','Invite '+b.name);btn.innerHTML=`<span class="avatar" style="--bot-color:#${b.color.toString(16)}">${b.name[0]}</span><span class="bot-copy"><strong>${b.name} <small>/ ${b.role}</small></strong><small>${b.desc}</small></span><span class="check">${selectedBots.has(b.id)?'✓':'＋'}</span>`;btn.onclick=()=>{selectedBots.has(b.id)?selectedBots.delete(b.id):selectedBots.add(b.id);renderBotChoices()};div.append(btn)}}
function updateRecord(){if(best.time)$('best').textContent=`${best.days} NIGHTS / ${Math.floor(best.time/60)}m ${Math.floor(best.time%60)}s`;}
function saveRecord(){if(!state)return;if(state.time>best.time)best={time:state.time,days:state.day-1,secrets:state.discoveries.length};save('still-here-record',best);updateRecord()}
function callsign(){let name=$('player-name').value.trim().slice(0,18)||'Wanderer';save('still-here-name',name);return name}
function applySettings(){document.body.classList.toggle('touch',settings.touch);sound.volume=settings.volume;if(renderer){const ratios={low:1,balanced:1.4,high:1.8};renderer.setPixelRatio(Math.min(devicePixelRatio,ratios[settings.quality]||1.4));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=settings.quality==='high';}save('still-here-settings',settings)}
function init3D(){renderer=new T.WebGLRenderer({canvas:$('scene'),antialias:true,powerPreference:'high-performance',alpha:false});renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.type=T.PCFSoftShadowMap;
 scene=new T.Scene();scene.background=new T.Color(0x68694b);scene.fog=new T.Fog(0x68694b,18,62);camera=new T.PerspectiveCamera(74,innerWidth/innerHeight,.06,85);camera.rotation.order='YXZ';scene.add(camera);
 hemi=new T.HemisphereLight(0xfff8d2,0x474938,1.9);scene.add(hemi);ambient=new T.AmbientLight(0xb9c5b1,.2);scene.add(ambient);sun=new T.DirectionalLight(0xf8f1cf,.75);sun.position.set(40,30,40);scene.add(sun);
 for(let i=0;i<4;i++){let l=new T.PointLight(0xfff3b0,19,14,2);scene.add(l);nearLights.push(l)}flash=new T.SpotLight(0xf3efd9,38,23,.58,.75,1.35);flashTarget=new T.Object3D();scene.add(flash,flashTarget);flash.target=flashTarget;flash.shadow.mapSize.set(512,512);flash.shadow.bias=-.002;flash.castShadow=true;hands=handsModel();camera.add(hands);hands.visible=false;
 world=new World(91827);view=new WorldView(scene,world);camera.position.set(68,1.65,73);camera.lookAt(63,1.65,45);applySettings();}
function resetWorld(seed){if(world?.seed===seed)return;view?.dispose();world=new World(seed);view=new WorldView(scene,world);}
function begin(seed,options,members){resetWorld(seed);sim=new Simulation(seed,options);for(const member of members)sim.addPlayer(member.id,member.name,member.color);sim.start();state=sim.snapshot();startView();}
function startView(){mode='playing';modal=null;lastMessage=0;lastEvent=0;lastHp=100;lastPhase=false;lastDiscovery=-1;cachedChat='';buildMode=false;prediction=null;input.yaw=0;input.pitch=0;accumulator=0;netAcc=0;keys.clear();touchMove={x:0,y:0};for(const id of ['menu','waiting','game-over','pause','chat-panel','map-panel','settings','guide'])hide(id);show('hud');hands.visible=true;view.actors.forEach(v=>view.dynamic.remove(v));view.actors.clear();sound.start();updateHUD();lockMouse();}
function lockMouse(){if(settings.touch||mode!=='playing'||modal)return;try{const promise=$('scene').requestPointerLock?.();promise?.catch(()=>{})}catch{}}
function unlock(){if(document.pointerLockElement)document.exitPointerLock();keys.clear();touchMove={x:0,y:0};input.mx=input.mz=0;touchSprint=false;touchJump=false;}
function closeModal(){if(modal)hide(modal);modal=null;if(mode==='playing')lockMouse();}
function openModal(id){if(mode==='playing'&&buildMode)setBuild(false);if(modal)hide(modal);modal=id;show(id);unlock();if(id==='chat-panel'){renderChat();setTimeout(()=>$('chat-input').focus(),80)}if(id==='map-panel')drawMap();if(id==='pause')$('pause-note').textContent=session?'Your team’s expedition keeps running while this menu is open.':'Your expedition is paused.';}
function returnMenu(){saveRecord();session?.close();session=null;sim=null;state=null;mode='menu';if(modal)hide(modal);modal=null;unlock();for(const id of ['hud','waiting','game-over','chat-panel','map-panel','pause'])hide(id);show('menu');hands.visible=false;setBuild(false);resetWorld(91827);$('host-lobby').disabled=false;$('join-lobby').disabled=false;$('network-status').textContent='1–4 players · private invite codes';view.dynamic.clear();view.actors.clear();view.builds.clear();for(const m of view.pickups.values())m.visible=true;}
function action(kind,data){if(mode!=='playing')return;sound.start();if(session&&!session.host)session.toHost({type:'action',action:kind,data:data||{}});else sim?.action(localId,kind,data||{});if(['use','eat','drink','heal'].includes(kind))sound.cue('pickup');if(kind==='build')sound.cue('build');}
function renderLobby(members,bots){if(mode==='playing')return;hide('menu');show('waiting');$('room-code').textContent=session.code;$('roster').innerHTML=members.map(p=>`<div class="roster-person"><span class="avatar" style="--bot-color:#${p.color.toString(16)}">${safe(p.name[0])}</span>${safe(p.name)}<small>${p.id===session.id?'YOU':'PLAYER'}</small></div>`).join('')+(bots||[]).map(id=>{let b=BOT_TYPES.find(x=>x.id===id);return `<div class="roster-person">${b.name}<small>${b.role} BOT</small></div>`}).join('');$('start-lobby').classList.toggle('hidden',!session.host);$('lobby-note').textContent=session.host?'Start whenever your team is ready. Players can also join later.':'Waiting for the host to start…';}
function newSession(){session?.close();const net=new Session({onStatus:text=>{$('network-status').textContent=text;$('lobby-note').textContent=text},onReady:(code,online)=>{if(session!==net)return;renderLobby(net.members,[...selectedBots]);$('lobby-note').textContent=online?'Invite your friends, then start the expedition.':'Same-device lobby ready. Internet signaling is unavailable on this connection.'},onLobby:(members,bots)=>{if(session===net)renderLobby(members,bots)},onError:text=>{toast(text);$('network-status').textContent=text;$('join-lobby').disabled=false;$('host-lobby').disabled=false},onJoined:p=>{if(sim){sim.addPlayer(p.id,p.name,p.color);sim.say('Radio',p.name+' joined the expedition.')}},onLeft:id=>{sim?.removePlayer(id)},onPacket:(p,id)=>{if(!sim||!net.members.some(m=>m.id===id))return;if(p.type==='input')sim.setInput(id,p.input);if(p.type==='action')sim.action(id,p.action,p.data||{});},onStart:p=>{sim=null;localId=net.id;resetWorld(p.seed);state=p.state;startView();},onState:s=>{if(!s||mode!=='playing')return;state=s;if(prediction){const p=s.players.find(x=>x.id===localId);if(p){const error=dist(prediction,p);if(error>3||p.down){prediction.x=p.x;prediction.z=p.z}else{prediction.x+=(p.x-prediction.x)*.3;prediction.z+=(p.z-prediction.z)*.3}prediction.y=p.y}}},onDisconnected:text=>{saveRecord();returnMenu();toast(text)}});session=net;return net;}
function setBuild(on){buildMode=on;if(ghost){scene?.remove(ghost);ghost.traverse(o=>{if(o.isMesh&&o.material.transparent)o.material.dispose()});ghost=null}if(!on){hide('build-hint');return}ghost=buildModel(buildKind,true);scene.add(ghost);show('build-hint');$('build-hint').innerHTML=`<div>Build a shelter · <span id="build-valid">Aim at open floor</span></div><button id="choose-wall" class="${buildKind==='wall'?'selected-build':''}">Barricade · 3</button><button id="choose-lamp" class="${buildKind==='lamp'?'selected-build':''}">Light · 2</button><button id="rotate-build">Rotate</button><button id="dismantle-build">Dismantle</button><button id="cancel-build">Done</button><div>${settings.touch?'USE to place':'Click to place · R rotate · X dismantle'}</div>`;$('choose-wall').onclick=()=>{buildKind='wall';setBuild(true)};$('choose-lamp').onclick=()=>{buildKind='lamp';setBuild(true)};$('rotate-build').onclick=()=>{buildRot+=Math.PI/2};$('cancel-build').onclick=()=>setBuild(false);$('dismantle-build').onclick=()=>action('dismantle');}
function buildAim(p){const ahead=3.1;const b={kind:buildKind,x:Math.round((p.x-Math.sin(input.yaw)*ahead)*2)/2,z:Math.round((p.z-Math.cos(input.yaw)*ahead)*2)/2,rot:buildRot};buildPosition=b;const can=sim?sim.canBuild({...b}):!world.blocked(b.x,b.z,1.2,state.builds);ghost.position.set(b.x,0,b.z);ghost.rotation.y=b.rot;ghost.traverse(o=>{if(o.isMesh)o.material.color.setHex(can?0xbde899:0xe99279)});$('build-valid').textContent=can?'Clear to place':'Move away from obstacles';}
function use(){if(buildMode&&buildPosition)action('build',buildPosition);else action('use')}
function pushOrPlace(){if(buildMode)use();else action('push')}
function player(){return state?.players.find(p=>p.id===localId)}
function readInput(){const active=mode==='playing'&&!modal;input.mx=active?clamp((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+touchMove.x,-1,1):0;input.mz=active?clamp((keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)+touchMove.y,-1,1):0;input.sprint=active&&(keys.has('ShiftLeft')||keys.has('ShiftRight')||touchSprint);input.jump=active&&(keys.has('Space')||touchJump);touchJump=false;}
function renderChat(){if(!state)return;const html=state.messages.map(m=>`<div class="chat-message ${m.echo?'echo':''}"><strong>${safe(m.name)}</strong>${safe(m.text)}</div>`).join('');if(html!==cachedChat){$('chat-history').innerHTML=html;cachedChat=html;$('chat-history').scrollTop=$('chat-history').scrollHeight}const feed=state.messages.filter(m=>state.time-m.time<22).slice(-3);$('chat-feed').innerHTML=feed.map(m=>`<div class="chat-message ${m.echo?'echo':''}"><strong>${safe(m.name)}</strong>${safe(m.text)}</div>`).join('');}
function updateHUD(){if(!state)return;const p=player();if(!p)return;const r=roomAt(p.x,p.z);$('sector').textContent=sector(p.x,p.z);$('room-name').textContent=r?.name||'THE YELLOW';const remaining=Math.max(0,Math.ceil((state.night?state.rules.night:state.rules.day)-state.phaseTime));$('phase').textContent=(state.night?'NIGHT ':'DAY ')+String(state.day).padStart(2,'0');$('clock').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');$('phase-hint').textContent=state.night?'UNTIL DAYLIGHT':'UNTIL LIGHTS OUT';$('cycle-fill').style.width=remaining/(state.night?state.rules.night:state.rules.day)*100+'%';document.body.classList.toggle('night',state.night);
 for(const [key,stat] of [['health','hp'],['food','food'],['water','water'],['stamina','stamina']]){$(key+'-value').textContent=Math.round(p[stat]);$(key+'-bar').style.width=Math.max(0,p[stat])+'%'}for(const key of ['food','water','med','scrap'])$('inv-'+key).textContent=p.inv[key];$('flash-state').textContent=p.flash?'ON':'OFF';$('team-list').innerHTML=[...state.bots,...state.players.filter(p=>p.id!==localId)].map(b=>`<div class="team-member" style="--bot-color:#${b.color.toString(16)}"><i></i>${safe(b.name)}<small>${b.down?'NEEDS HELP':safe(b.status||'Exploring')} · ${Math.round(dist(b,p))}m</small></div>`).join('');
 if(p.hp<lastHp){sound.cue('hurt');$('damage').style.opacity='.8';clearTimeout(damageTimer);damageTimer=setTimeout(()=>$('damage').style.opacity='0',400)}lastHp=p.hp;
 if(p.down){show('interaction');$('interaction').querySelector('span').textContent='Downed · Waiting for a teammate to help you';}else{let target;if(sim)target=sim.interactable(p);else{const found=state.pickups.filter(i=>i.active&&dist(i,p)<2.9).find(i=>{let dx=i.x-p.x,dz=i.z-p.z;return (-Math.sin(p.yaw)*dx-Math.cos(p.yaw)*dz)/Math.max(.01,dist(p,i))>.66&&world.visible(p,i)});if(found)target={type:'pickup',p:found};const down=[...state.players,...state.bots].find(x=>x.down&&dist(x,p)<2.7);if(down)target={type:'revive',p:down};}if(target&&!buildMode){show('interaction');$('interaction').querySelector('span').textContent=target.type==='revive'?'Help '+target.p.name+' up':'Take '+({food:'rations',water:'water bottle',med:'medkit',scrap:'salvaged material'}[target.p.type]);}else hide('interaction')}
 for(const m of state.messages)if(m.id>lastMessage){lastMessage=m.id;if(state.time-m.time<2){sound.cue('radio');if(settings.voice&&!m.echo&&state.bots.some(b=>b.name===m.name)&&'speechSynthesis'in window){let u=new SpeechSynthesisUtterance(m.text);u.rate=1.03;u.volume=settings.volume;u.pitch=m.name==='Dex'?.85:1;window.speechSynthesis.speak(u)}}}for(const e of state.events)if(e.id>lastEvent){lastEvent=e.id;if(state.time-e.time<6){if(e.text&&(!e.target||e.target===localId))toast(e.text);else if(e.title)banner(e.kicker,e.title)}}renderChat();if(lastPhase!==state.night){lastPhase=state.night;if(state.night)sound.cue('night');saveRecord()}if(state.finished&&mode==='playing'){saveRecord();mode='over';unlock();hide('hud');show('game-over');$('results').textContent=`You survived ${Math.floor(state.time/60)}m ${Math.floor(state.time%60)}s, outlasted ${state.day-1} nights, and discovered ${state.discoveries.length} of 5 secret rooms. The next expedition starts with new corridors.`;if(modal){hide(modal);modal=null}}
 if(modal==='map-panel')drawMap();
 }
function drawMap(){if(!state)return;const c=$('map-canvas'),ctx=c.getContext('2d'),s=5;ctx.fillStyle='#0b140e';ctx.fillRect(0,0,650,650);for(const id of state.explored){const x=id%13,z=Math.floor(id/13),r=roomAt(x*10+5,z*10+5);ctx.fillStyle=r?'#4b6141':'#303a29';ctx.fillRect(x*50,z*50,50,50)}ctx.strokeStyle='#99a47a';ctx.lineWidth=2;for(const wall of world.walls){let cells=[Math.floor((wall.z-.3)/10)*13+Math.floor((wall.x-.3)/10),Math.floor((wall.z+.3)/10)*13+Math.floor((wall.x+.3)/10)];if(!cells.some(id=>state.explored.includes(id)))continue;ctx.strokeRect((wall.x-wall.w/2)*s,(wall.z-wall.d/2)*s,wall.w*s,wall.d*s)}for(const r of ROOMS)if(r.id==='arrival'||state.discoveries.includes(r.id)){ctx.fillStyle='#d5dfba';ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText(r.id.toUpperCase(),(r.x+r.w/2)*50,(r.z+r.h/2)*50-10)}for(const b of state.builds){ctx.fillStyle=b.kind==='lamp'?'#f3dc90':'#af916a';ctx.fillRect(b.x*s-3,b.z*s-3,6,6)}for(const p of [...state.players,...state.bots]){ctx.fillStyle=p.id===localId?'#edf4bc':'#'+p.color.toString(16);ctx.beginPath();ctx.arc(p.x*s,p.z*s,p.id===localId?5:3.5,0,Math.PI*2);ctx.fill();if(p.id===localId){ctx.strokeStyle='#eff5c3';ctx.beginPath();ctx.moveTo(p.x*s,p.z*s);ctx.lineTo((p.x-Math.sin(input.yaw)*3)*s,(p.z-Math.cos(input.yaw)*3)*s);ctx.stroke()}}}
function renderFrame(now){const dt=Math.min(.06,(now-lastNow)/1000);lastNow=now;requestAnimationFrame(renderFrame);if(!renderer)return;const t=now/1000;
 if(mode==='playing'){readInput();const paused=!session&&modal&&modal!=='chat-panel';if(!paused){if(sim){sim.setInput(localId,input);accumulator+=dt;while(accumulator>=.05){sim.tick(.05);accumulator-=.05}state=sim.snapshot();}netAcc+=dt;if(session&&netAcc>=.07){if(session.host&&sim)session.broadcast({type:'state',state});else session.toHost({type:'input',input});netAcc=0;}}const p=player();if(p){let position=p;if(session&&!session.host&&!p.down){if(!prediction)prediction={x:p.x,z:p.z,y:p.y};let len=Math.max(1,Math.hypot(input.mx,input.mz)),speed=input.sprint&&p.stamina>2?5.5:3.15;if(!modal)world.move(prediction,(input.mx*Math.cos(input.yaw)+input.mz*Math.sin(input.yaw))/len*speed*dt,(-input.mx*Math.sin(input.yaw)+input.mz*Math.cos(input.yaw))/len*speed*dt,state.builds);position=prediction;}bob+=p.moving?dt*(input.sprint?12:8):dt;const sway=settings.motion?0:(p.moving?Math.sin(bob)*.026:Math.sin(t*1.7)*.006);const targetY=(p.down?.55:1.66)+(position.y||0)+sway;camera.position.x+=(position.x-camera.position.x)*(1-Math.exp(-dt*22));camera.position.z+=(position.z-camera.position.z)*(1-Math.exp(-dt*22));camera.position.y+=(targetY-camera.position.y)*(1-Math.exp(-dt*18));camera.rotation.set(input.pitch,input.yaw,settings.motion?0:sway*.13,'YXZ');hands.visible=!p.down;hands.position.y=sway*.7;hands.position.x=settings.motion?0:Math.cos(bob/2)*(p.moving?.007:.002);if(buildMode)buildAim(p);view.sync(state,localId,dt,t);sound.update(p,state,t);hudAcc+=dt;if(hudAcc>.12){updateHUD();hudAcc=0;}}}
 else if(mode==='menu'||mode==='lobby'){camera.position.set(68+Math.sin(t*.08)*.7,1.67,73);camera.lookAt(63+Math.cos(t*.065)*1.3,1.7,45);hands.visible=false;view.lampMat.color.setHex(0xfff9c4);}
 const targetLight=state?.night&&mode!=='menu'?.06:1;lightLevel+=(targetLight-lightLevel)*(1-Math.exp(-dt*1.6));hemi.intensity=.13+1.77*lightLevel;ambient.intensity=.1+.1*lightLevel;sun.intensity=.04+.71*lightLevel;scene.fog.color.setRGB(.024+.32*lightLevel,.034+.32*lightLevel,.027+.20*lightLevel);scene.background.copy(scene.fog.color);scene.fog.near=state?.night?12:20;scene.fog.far=state?.night?43:64;
 const cx=Math.floor(camera.position.x/10)*10+5,cz=Math.floor(camera.position.z/10)*10+5;const cells=[[cx,cz],[cx+10,cz],[cx,cz-10],[cx-10,cz]];nearLights.forEach((l,i)=>{l.position.set(cells[i][0],3.32,cells[i][1]);l.intensity=19*lightLevel;});if(state){const lamps=state.builds.filter(b=>b.kind==='lamp'&&dist(b,camera.position)<18);if(lamps.length){const b=lamps[0];nearLights[3].position.set(b.x,1.9,b.z);nearLights[3].intensity=22;}}
 const direction=new T.Vector3(0,0,-1).applyQuaternion(camera.quaternion);flash.position.copy(camera.position).add(new T.Vector3(.14,-.15,0).applyQuaternion(camera.quaternion));flashTarget.position.copy(camera.position).addScaledVector(direction,20);flash.intensity=mode==='playing'&&player()?.flash?38:0;
 renderer.render(scene,camera);
}
function initUI(){renderBotChoices();updateRecord();$('player-name').value=saved('still-here-name','Wanderer');const params=new URLSearchParams(location.search);if(params.has('join')){$('join-code').value=params.get('join').replace(/[^a-z0-9]/gi,'').slice(0,6).toUpperCase();$('network-status').textContent='Invite received. Enter a callsign and press Join.';}
 $('play-solo').onclick=()=>{localId='solo';begin(crypto.getRandomValues(new Uint32Array(1))[0],{bots:[...selectedBots],difficulty:$('difficulty').value},[{id:localId,name:callsign(),color:0x9cab71}])};$('host-lobby').onclick=()=>{$('host-lobby').disabled=true;mode='lobby';newSession().hostRoom(callsign(),[...selectedBots]);};$('join-lobby').onclick=()=>{const code=$('join-code').value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(code)){toast('Enter the six-character lobby code.');return}$('join-lobby').disabled=true;mode='lobby';newSession().joinRoom(code,callsign());};$('leave-lobby').onclick=returnMenu;$('start-lobby').onclick=()=>{if(!session?.host)return;localId=session.id;const seed=crypto.getRandomValues(new Uint32Array(1))[0];begin(seed,{bots:session.bots,difficulty:$('difficulty').value},session.members);session.started=true;session.getWelcome=()=>({seed,state:sim.snapshot()});session.broadcast({type:'start',...session.getWelcome()})};$('copy-invite').onclick=async()=>{const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('join',session.code);try{await navigator.clipboard.writeText(url.href);toast('Invite link copied.')}catch{toast('Lobby code: '+session.code)}};
 for(const id of ['guide-open','pause-guide'])$(id).onclick=()=>openModal('guide');$('guide-close').onclick=closeModal;for(const id of ['settings-open','pause-settings'])$(id).onclick=()=>{settingsReturn=modal;openModal('settings')};$('settings-close').onclick=()=>{closeModal();if(settingsReturn==='pause')openModal('pause');settingsReturn=null};$('pause-open').onclick=()=>openModal('pause');$('resume').onclick=closeModal;$('quit').onclick=returnMenu;$('retry').onclick=returnMenu;$('chat-open').onclick=()=>openModal('chat-panel');$('chat-close').onclick=closeModal;$('map-open').onclick=()=>openModal('map-panel');$('map-close').onclick=closeModal;
 $('chat-form').onsubmit=e=>{e.preventDefault();const text=$('chat-input').value.trim();if(!text)return;action('chat',{text});$('chat-input').value='';setTimeout(()=>{if(sim)state=sim.snapshot();renderChat()},100)};for(const b of document.querySelectorAll('[data-order]'))b.onclick=()=>{action('chat',{text:b.dataset.order});setTimeout(()=>{if(sim)state=sim.snapshot();renderChat()},100)};for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>action(b.dataset.action);$('build-toggle').onclick=()=>setBuild(!buildMode);$('flash-toggle').onclick=()=>action('flash');$('touch-use').onclick=use;$('touch-push').onclick=pushOrPlace;$('touch-jump').onpointerdown=e=>{e.preventDefault();touchJump=true};$('touch-sprint').onpointerdown=e=>{e.preventDefault();touchSprint=true;$('touch-sprint').setPointerCapture(e.pointerId)};$('touch-sprint').onpointerup=$('touch-sprint').onpointercancel=()=>touchSprint=false;
 $('quality').value=settings.quality;$('sensitivity').value=settings.sensitivity;$('volume').value=settings.volume;$('voice').checked=settings.voice;$('motion').checked=settings.motion;$('touch-mode').checked=settings.touch;for(const [id,key] of [['quality','quality'],['sensitivity','sensitivity'],['volume','volume'],['voice','voice'],['motion','motion'],['touch-mode','touch']])$(id).oninput=()=>{const el=$(id);settings[key]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;applySettings()};
 document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)){if(e.code==='Escape')closeModal();return}if(mode!=='playing')return;if(e.code==='Escape'){e.preventDefault();modal?closeModal():openModal('pause');return}if(modal)return;keys.add(e.code);if(['Space','KeyW','KeyA','KeyS','KeyD','Tab'].includes(e.code))e.preventDefault();if(e.repeat)return;const commands={KeyE:use,Digit1:()=>action('eat'),Digit2:()=>action('drink'),Digit3:()=>action('heal'),KeyF:()=>action('flash'),KeyB:()=>setBuild(!buildMode),KeyR:()=>buildRot+=Math.PI/2,KeyX:()=>action('dismantle'),KeyT:()=>openModal('chat-panel'),Enter:()=>openModal('chat-panel'),KeyM:()=>openModal('map-panel')};commands[e.code]?.();});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();touchMove={x:0,y:0};touchSprint=false;});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&mode==='playing'&&!modal&&!settings.touch)openModal('pause')});document.addEventListener('mousemove',e=>{if(document.pointerLockElement=== $('scene')&&mode==='playing'&&!modal){input.yaw-=e.movementX*.002*settings.sensitivity;input.pitch=clamp(input.pitch-e.movementY*.002*settings.sensitivity,-1.25,1.25)}});
 let look=null;$('scene').onpointerdown=e=>{if(mode!=='playing'||modal)return;sound.start();if(e.pointerType==='touch'||!document.pointerLockElement){look={id:e.pointerId,x:e.clientX,y:e.clientY};$('scene').setPointerCapture(e.pointerId)}else pushOrPlace()};$('scene').onpointermove=e=>{if(look?.id!==e.pointerId||modal)return;input.yaw-=(e.clientX-look.x)*.004*settings.sensitivity;input.pitch=clamp(input.pitch-(e.clientY-look.y)*.004*settings.sensitivity,-1.25,1.25);look.x=e.clientX;look.y=e.clientY};$('scene').onpointerup=$('scene').onpointercancel=e=>{if(look?.id===e.pointerId)look=null};$('scene').ondblclick=lockMouse;$('scene').oncontextmenu=e=>e.preventDefault();let joyId=null;const joy=$('joystick'),knob=joy.querySelector('span');function moveJoy(e){const r=joy.getBoundingClientRect(),rad=r.width/2-15,dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),len=Math.max(1,Math.hypot(dx,dy)/rad);touchMove={x:dx/len/rad,y:dy/len/rad};knob.style.transform=`translate(${dx/len}px,${dy/len}px)`}joy.onpointerdown=e=>{e.preventDefault();joyId=e.pointerId;joy.setPointerCapture(joyId);moveJoy(e)};joy.onpointermove=e=>{if(e.pointerId===joyId)moveJoy(e)};joy.onpointerup=joy.onpointercancel=()=>{joyId=null;touchMove={x:0,y:0};knob.style.transform=''};
 window.addEventListener('resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});window.addEventListener('pagehide',()=>saveRecord());$('scene').addEventListener('webglcontextlost',e=>{e.preventDefault();if(mode==='playing')openModal('pause');toast('Graphics were interrupted. Reload the page to restore the world.');});
}
try{initUI();init3D();hide('boot');show('menu');requestAnimationFrame(renderFrame);}catch(e){console.error(e);$('boot-status').textContent='The 3D renderer could not start. Enable WebGL in your browser and reload. '+e.message;}
