// Host-authoritative state over WebRTC. BroadcastChannel is only a same-device fallback.
export class Session{
 constructor(callbacks={}){Object.assign(this,callbacks);this.id=crypto.randomUUID();this.peer=null;this.links=new Map();this.members=[];this.host=false;this.code='';this.started=false;this.closed=false;this.seen=new Set();this.transport='';this.timer=null;this.keepalive=null;this.name='Wanderer';this.localLinks=new Set();}
 hostRoom(name,bots){this.host=true;this.name=name;this.bots=bots;const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',bytes=crypto.getRandomValues(new Uint8Array(6));this.code=Array.from(bytes,b=>alphabet[b%alphabet.length]).join('');this.members=[{id:this.id,name,color:0x9cab71}];this.setupChannel();this.onStatus?.('Opening an internet lobby…');this.setupPeer(true);}
 joinRoom(code,name){this.host=false;this.code=code.toUpperCase().replace(/[^A-Z0-9]/g,'');this.name=name;this.setupChannel();this.onStatus?.('Looking for the host…');this.setupPeer(false);this.channel?.postMessage({type:'hello',from:this.id,name});this.timer=setTimeout(()=>{if(!this.members.length&&!this.closed)this.onError?.('Could not reach that lobby. Check the code and that the host’s tab is open. Some networks block WebRTC.');},16000);}
 setupChannel(){if(new URLSearchParams(location.search).has('webrtc'))return;try{this.channel=new BroadcastChannel('still-here-'+this.code);this.channel.onmessage=e=>{const m=e.data;if(!m||m.from===this.id||m.to&&m.to!==this.id)return;if(this.host&&m.type==='hello'){this.localLinks.add(m.from);this.accept(m.from,m.name,'same-device');}else if(!this.host&&m.type==='welcome'){this.localHost=m.from;this.transport='same-device';this.receive(m.payload,m.from);}else if(this.host&&this.localLinks.has(m.from)&&m.type==='packet')this.onPacket?.(m.payload,m.from);else if(!this.host&&m.from===this.localHost&&m.type==='packet')this.receive(m.payload,m.from);else if(this.host&&m.type==='leave'){this.drop(m.from);}}}catch{this.channel=null}}
 setupPeer(isHost){if(typeof Peer==='undefined'){this.onStatus?.('Internet signaling unavailable. Solo and same-device lobbies still work.');if(isHost)this.onReady?.(this.code,false);return}this.peer=new Peer(isHost?'still-here-v1-'+this.code:undefined,{debug:0});this.peer.on('open',()=>{if(this.closed)return;if(isHost){this.onStatus?.('Internet lobby ready. Share the invite.');this.onReady?.(this.code,true);this.onLobby?.(this.members,this.bots);}else{const c=this.peer.connect('still-here-v1-'+this.code,{reliable:true,serialization:'json',metadata:{id:this.id,name:this.name}});this.bind(c,false);}});this.peer.on('connection',c=>{if(isHost)this.bind(c,true);else c.close()});this.peer.on('error',e=>{if(this.closed)return;const message=e.type==='peer-unavailable'?'The host wasn’t found. Check the invite code.':'Internet connection unavailable on this network.';if(isHost){this.onStatus?.(message+' Same-device lobby is available.');this.onReady?.(this.code,false);this.onLobby?.(this.members,this.bots);}else if(!this.members.length)this.onStatus?.(message);});this.peer.on('disconnected',()=>{if(!this.closed&&this.peer&&!this.peer.destroyed){this.onStatus?.('Signaling disconnected. Existing players can keep playing.');try{this.peer.reconnect()}catch{}}});if(isHost)this.timer=setTimeout(()=>{if(!this.peer?.open&&!this.closed){this.onStatus?.('Internet signaling timed out. Same-device lobby is available.');this.onReady?.(this.code,false);this.onLobby?.(this.members,this.bots);}},12000);}
 bind(c,incoming){const id=incoming?c.metadata?.id:'host';if(typeof id!=='string'){c.close();return}c.on('open',()=>{if(this.closed){c.close();return}if(incoming){if(this.localLinks.has(id)){c.close();return}if(this.members.length>=4&&!this.members.some(m=>m.id===id)){c.send({type:'error',text:'This lobby is full (4 players).'});setTimeout(()=>c.close(),150);return}this.links.set(id,c);this.accept(id,c.metadata?.name,'WebRTC');}else{if(this.localHost){c.close();return}this.links.set('host',c);this.transport='WebRTC';}});c.on('data',data=>{if(!data||typeof data!=='object')return;if(incoming){if(this.links.get(id)===c)this.onPacket?.(data,id)}else if(!this.localHost)this.receive(data,'host')});c.on('close',()=>{if(incoming){if(this.links.get(id)===c){this.links.delete(id);this.drop(id)}}else if(!this.closed&&!this.localHost&&this.links.get('host')===c)this.onDisconnected?.('The host disconnected. This expedition has ended.');});c.on('error',()=>{if(!this.closed&&!incoming&&!this.localHost)this.onStatus?.('Connection interrupted. Keep the host tab open.');});}
 accept(id,name,transport){if(this.members.length>=4&&!this.members.some(m=>m.id===id)){this.send(id,{type:'error',text:'This lobby is full (4 players).'});return}if(!this.members.some(m=>m.id===id)){const colors=[0x9cab71,0x87bdb2,0xd3a262,0xb2bde0];this.members.push({id,name:String(name||'Wanderer').slice(0,18),color:colors[this.members.length]});this.onJoined?.(this.members[this.members.length-1]);}this.send(id,{type:'lobby',members:this.members,bots:this.bots,code:this.code,transport});this.broadcast({type:'lobby',members:this.members,bots:this.bots,code:this.code});this.onLobby?.(this.members,this.bots);if(this.started&&this.getWelcome)this.send(id,{type:'start',...this.getWelcome()});}
 receive(p,from){if(p.type==='lobby'){clearTimeout(this.timer);this.members=p.members;this.bots=p.bots;this.code=p.code;this.onStatus?.('Connected · '+this.transport);this.onLobby?.(this.members,this.bots)}else if(p.type==='start'){this.started=true;this.onStart?.(p)}else if(p.type==='state'){this.onState?.(p.state)}else if(p.type==='error'){this.onError?.(p.text)}else if(p.type==='end'){this.onDisconnected?.(p.text||'The host ended this expedition.')}}
 send(id,payload){if(this.host&&this.localLinks.has(id)){this.channel?.postMessage({type:payload.type==='lobby'?'welcome':'packet',from:this.id,to:id,payload});return}const c=this.links.get(id);if(c?.open&&(!c.dataChannel||c.dataChannel.bufferedAmount<200000))try{c.send(payload)}catch{}}
 toHost(payload){if(this.localHost){this.channel?.postMessage({type:'packet',from:this.id,to:this.localHost,payload});return}this.send('host',payload)}
 broadcast(payload){for(const m of this.members)if(m.id!==this.id)this.send(m.id,payload)}
 drop(id){this.localLinks.delete(id);this.members=this.members.filter(m=>m.id!==id);this.onLeft?.(id);this.broadcast({type:'lobby',members:this.members,bots:this.bots,code:this.code});this.onLobby?.(this.members,this.bots)}
 close(){if(this.host)this.broadcast({type:'end',text:'The host ended this expedition.'});else this.channel?.postMessage({type:'leave',from:this.id});this.closed=true;clearTimeout(this.timer);clearInterval(this.keepalive);for(const c of this.links.values())c.close();this.links.clear();this.peer?.destroy();this.channel?.close();}
}
