import {BOT_TYPES,ROOMS,World,dist,clamp,roomAt,sector} from './world.js';
export const RULES={calm:{day:220,night:85,damage:6,speed:.84,drain:.7},normal:{day:180,night:100,damage:10,speed:1,drain:1},hard:{day:150,night:120,damage:14,speed:1.12,drain:1.2}};
export class Simulation{
 constructor(seed,options={}){this.world=new World(seed);this.seed=seed;this.difficulty=options.difficulty||'normal';this.rules=RULES[this.difficulty]||RULES.normal;this.time=0;this.phaseTime=0;this.day=1;this.night=false;this.players=[];this.bots=[];this.enemies=[];this.builds=[];this.pickups=this.world.pickups.map(p=>({...p}));this.messages=[];this.events=[];this.explored=[];this.discoveries=[];this.inputs=new Map();this.finished=false;this.counter=0;this.npcClock=0;this.lastSpawn=0;this.chatMemory=[];this.visits=new Set();for(const id of options.bots||[])this.addBot(id);}
 person(id,name,color,bot=false){let pos=this.world.freeNear(65,65,bot?3.5:1.5);return {id,name:String(name).slice(0,18),color,...pos,y:0,vy:0,yaw:0,pitch:0,hp:100,food:100,water:100,stamina:100,inv:{food:2,water:2,med:1,scrap:8},down:false,downTime:0,hurtUntil:0,pushUntil:0,flash:true,moving:false,bot,order:'follow',targetPlayer:null,nav:[],navAt:0,planAt:0,status:'Following',lastTalk:-30,revive:0};}
 addPlayer(id,name,color=0x9cab71){if(this.players.some(p=>p.id===id))return;const p=this.person(id,name,color);this.players.push(p);if(this.players.length===1){p.x=65;p.z=65;p.yaw=0;for(const b of this.bots)b.targetPlayer=id;}return p;}
 removePlayer(id){this.players=this.players.filter(p=>p.id!==id);this.inputs.delete(id);for(const b of this.bots)if(b.targetPlayer===id)b.targetPlayer=this.players[0]?.id;}
 addBot(id){const def=BOT_TYPES.find(b=>b.id===id);if(!def||this.bots.some(b=>b.id===id))return;let b=this.person(def.id,def.name,def.color,true);Object.assign(b,{role:def.role,inv:{food:3,water:3,med:def.id==='sol'?4:1,scrap:def.id==='dex'?18:6},targetPlayer:this.players[0]?.id||null});this.bots.push(b);}
 say(name,text,echo=false){this.messages.push({id:++this.counter,name,text:String(text).slice(0,240),time:this.time,echo});if(this.messages.length>45)this.messages.shift();}
 announce(kicker,title){this.events.push({id:++this.counter,kicker,title,time:this.time});if(this.events.length>8)this.events.shift()}
 toast(id,text){this.events.push({id:++this.counter,target:id,text,time:this.time});if(this.events.length>8)this.events.shift()}
 start(){this.announce('EXPEDITION 01 / LIGHTS ON','Make it to morning.');this.say('Radio','Find supplies, build a shelter, and survive as long as you can.');if(this.bots.length)this.say(this.bots[0].name,'We have daylight. I’m with you. Ask us to gather, build, follow, or find a room.');}
 setInput(id,input){const p=this.players.find(p=>p.id===id);if(!p||!input)return;this.inputs.set(id,{mx:clamp(Number(input.mx)||0,-1,1),mz:clamp(Number(input.mz)||0,-1,1),yaw:Number.isFinite(input.yaw)?input.yaw:p.yaw,pitch:clamp(Number(input.pitch)||0,-1.3,1.3),sprint:!!input.sprint,jump:!!input.jump,at:this.time});}
 action(id,action,data={}){const p=this.players.find(p=>p.id===id);if(!p||this.finished)return;if(p.down){if(action==='chat')this.chat(p,data.text);return;}if(action==='chat'){this.chat(p,data.text);return;}
 if(action==='flash'){p.flash=!p.flash;return}if(action==='eat'||action==='drink'||action==='heal'){const key=action==='eat'?'food':action==='drink'?'water':'med';if(!p.inv[key])return this.toast(id,'No '+(key==='med'?'medkits':key)+' left. Ask your team or scavenge.');const stat=key==='med'?'hp':key;if(p[stat]>=98)return this.toast(id,'Already full. Save it for later.');p.inv[key]--;p[stat]=Math.min(100,p[stat]+(key==='med'?48:44));this.toast(id,key==='med'?'Medkit used. Health restored.':key==='food'?'Rations eaten.':'Water replenished.');return;}
 if(action==='use'){let target=this.interactable(p);if(target?.type==='revive'){this.revive(p,target.p);return}if(target?.type==='pickup'){let i=target.p;if(this.world.visible(p,i,this.builds)){i.active=false;let amount=i.type==='scrap'?3:1;p.inv[i.type]=Math.min(99,p.inv[i.type]+amount);this.toast(id,`+${amount} ${i.type==='med'?'medkit':i.type}`)}return}}
 if(action==='build'){if(!['wall','lamp'].includes(data.kind)||!Number.isFinite(data.x)||!Number.isFinite(data.z))return;const rot=Math.round((data.rot||0)/(Math.PI/2))*Math.PI/2;let b={kind:data.kind,x:data.x,z:data.z,rot};if(dist(p,b)>4.5)return;const cost=b.kind==='wall'?3:2;if(p.inv.scrap<cost)return this.toast(id,'Need '+cost+' salvaged material.');if(!this.canBuild(b))return this.toast(id,'Not enough room. Move the outline away from obstacles and teammates.');p.inv.scrap-=cost;this.place(b,p.id);this.toast(id,b.kind==='wall'?'Barricade placed.':'Work light placed.');return}
 if(action==='dismantle'){let b=this.builds.filter(b=>b.hp>0&&dist(p,b)<3.6&&this.inFront(p,b,.55)).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(b){b.hp=0;p.inv.scrap=Math.min(99,p.inv.scrap+(b.kind==='wall'?2:1));this.toast(id,'Dismantled. Material recovered.')}return}
 if(action==='push'&&this.time>p.pushUntil){p.pushUntil=this.time+1.15;let hit=false;for(const e of this.enemies)if(dist(p,e)<2.6&&this.inFront(p,e,.05)&&this.world.visible(p,e)){e.stun=this.time+2.5;let d=Math.max(.01,dist(p,e));this.world.move(e,(e.x-p.x)/d*1.8,(e.z-p.z)/d*1.8,this.builds);hit=true}if(hit)this.toast(id,'Shoved it back. Move!');}
 }
 inFront(p,q,threshold=.55){let dx=q.x-p.x,dz=q.z-p.z,d=Math.hypot(dx,dz)||1;return (-Math.sin(p.yaw)*dx-Math.cos(p.yaw)*dz)/d>threshold}
 interactable(p){let down=[...this.players,...this.bots].find(b=>b.id!==p.id&&b.down&&dist(p,b)<2.7&&this.inFront(p,b,.1)&&this.world.visible(p,b));if(down)return {type:'revive',p:down};const item=this.pickups.filter(i=>i.active&&dist(i,p)<2.9&&this.inFront(p,i,.66)&&this.world.visible(p,i)).sort((a,b)=>dist(a,p)-dist(b,p))[0];return item?{type:'pickup',p:item}:null}
 dimensions(b){const sideways=Math.abs(Math.sin(b.rot))>.7;return b.kind==='wall'?{w:sideways?.8:2.45,d:sideways?2.45:.8,h:1.45}:{w:.65,d:.65,h:1.85}}
 canBuild(b){Object.assign(b,this.dimensions(b));if(this.builds.filter(b=>b.hp>0).length>=70)return false;for(const a of [...this.world.solids,...this.builds.filter(b=>b.hp>0)])if(Math.abs(b.x-a.x)<(b.w+a.w)/2+.12&&Math.abs(b.z-a.z)<(b.d+a.d)/2+.12)return false;for(const p of [...this.players,...this.bots,...this.enemies])if(this.world.overlap(p.x,p.z,.5,b))return false;return b.x-b.w/2>.5&&b.z-b.d/2>.5&&b.x+b.w/2<129.5&&b.z+b.d/2<129.5}
 place(b,owner){Object.assign(b,this.dimensions(b),{id:'b'+(++this.counter),hp:b.kind==='wall'?125:75,owner});this.builds.push(b);for(const bot of this.bots)bot.navAt=0;}
 revive(helper,p){if(!p.down||dist(helper,p)>2.8||!this.world.visible(helper,p))return false;p.down=false;p.hp=40;p.food=Math.max(25,p.food);p.water=Math.max(25,p.water);p.downTime=0;p.hurtUntil=this.time+6;if(helper.inv.med>0){helper.inv.med--;p.hp=65}this.say(helper.name,`${p.name}, you’re back up. Stay close.`);return true}
 chat(p,text){if(typeof text!=='string')return;text=text.trim().slice(0,180);if(!text||this.time-(p.lastChat||-10)<.5)return;p.lastChat=this.time;this.say(p.name,text);this.chatMemory.push({name:p.name,color:p.color,text});if(this.chatMemory.length>12)this.chatMemory.shift();if(!this.bots.length)return;const s=text.toLowerCase(),named=this.bots.filter(b=>s.includes(b.name.toLowerCase()));const all=/everyone|everybody|team|all of you/.test(s);const relevant=/heal|hurt|health|med|revive/.test(s)?'sol':/build|shelter|barricade/.test(s)?'dex':'mira';let respondents=named.length?named:all?this.bots:[this.bots.find(b=>b.id===relevant)||this.bots[0]];
 for(const b of respondents){b.targetPlayer=p.id;b.navAt=0;let answer='';const supply=/food|water|suppl|ration|scrap|material|medkit/.test(s),question=/where|how|what|when|why|can you|do you/.test(s);let room=ROOMS.find(r=>r.id!=='arrival'&&(s.includes(r.id)||s.includes(r.name.toLowerCase())||(r.id==='chairs'&&/chair/.test(s))||(r.id==='house'&&/home/.test(s))||(r.id==='garden'&&/conservatory/.test(s))));
 if(b.down)answer='I’m down. Come close and use the revive action; then I can help.';
 else if(/follow|come with|stay close|come here|regroup/.test(s)){b.order='follow';b.status='Following';answer=`On you, ${p.name}. I’ll keep a little space and watch the corridors.`;}
 else if(/wait|stay here|hold position|stop/.test(s)){b.order='wait';b.anchor={x:b.x,z:b.z};b.status='Holding';answer=`Holding at ${sector(b.x,b.z)}. Tell me to follow when you move.`;}
 else if(/build|shelter|barricade/.test(s)){b.order='build';b.anchor={x:p.x,z:p.z};b.buildCount=0;b.status='Building';answer=b.inv.scrap>=3?'I’ll put barricades around this position and leave a way out. Stay clear of the placement area.':'I need more material first. I’ll gather some and come back.';}
 else if(/heal|hurt|health|revive|help me|save me/.test(s)){b.order='help';b.status='Assisting';answer=p.hp>85&&!p.down?'Your health looks good. I’ll stay close and share supplies if you need them.':`Coming to you. ${b.inv.med?'I have a medkit.':'I can still help you back up.'}`;}
 else if(room){b.order='explore';b.exploreGoal={x:(room.x+room.w/2)*10,z:(room.z+room.h/2)*10};b.goal=b.exploreGoal;b.status='Finding '+room.id;answer=`${room.name} is around ${sector(b.goal.x,b.goal.z)}. I’ll lead; follow my suit color. ${this.night?'It’s dark, so keep your light on.':''}`;}
 else if(supply&&/find|gather|fetch|bring|need|collect|scavenge|get|give|share/.test(s)){b.order='gather';b.want=/scrap|material/.test(s)?'scrap':/medkit/.test(s)?'med':/water/.test(s)&&!/food/.test(s)?'water':/food/.test(s)&&!/water/.test(s)?'food':null;b.status='Scavenging';b.returning=false;answer=`I’ll look for ${b.want||'food and water'} and bring supplies back to you. Keep your radio on.`;}
 else if(/where|location|lost/.test(s)){answer=`You’re in ${roomAt(p.x,p.z)?.name||'THE YELLOW'}, sector ${sector(p.x,p.z)}. I’m at ${sector(b.x,b.z)}, ${Math.round(dist(p,b))} meters away. The arrival room is G7. Ask me to follow you or lead you to a secret.`;}
 else if(/time|night|dark|lights|morning/.test(s)){let secs=Math.ceil((this.night?this.rules.night:this.rules.day)-this.phaseTime);answer=`${this.night?'Daylight':'Lights out'} in ${Math.floor(secs/60)}m ${secs%60}s. ${this.night?'Use barriers, keep moving, and don’t follow a copy.':'Gather water first, then build before the lights switch.'}`;}
 else if(/still|cop(y|ies)|clone|mimic|yourself/.test(s)){answer='The rooms can copy your suit and repeat your radio messages. Check their proportions and movements. They never appear on the team list. Keep distance and shove them if they get close.';}
 else if(/entit|monster|watcher/.test(s)){answer='Stalkers chase noise. Watchers slow under a flashlight. Still Lifes mimic people. Barricades buy time, but none last forever. We can outrun them together.';}
 else if(/how.*(win|survive)|strategy|plan|what.*do|help/.test(s)){answer=`${this.night?'Survive until the lights return. Use barricades to buy time and sprint only when chased.':'Fill your bag with water and food, then build a shelter with an escape gap.'} There’s no final wave; the goal is a longer run. I can follow, gather, build, heal, or lead to a secret.`;}
 else if(/status|inventory|have|supplies/.test(s)){answer=`I have ${b.inv.food} food, ${b.inv.water} water, ${b.inv.med} medkits, and ${b.inv.scrap} material. Health ${Math.round(b.hp)}. Current task: ${b.status.toLowerCase()}.`;}
 else if(/who|name|hello|hey|hi\b/.test(s)){answer=`${b.name}, your ${b.role.toLowerCase()}. ${b.id==='mira'?'I scout and fetch supplies.':b.id==='dex'?'I build barricades and keep a route open.':'I heal and help teammates back up.'} What do you need?`;}
 else if(/thank|good job|nice/.test(s)){answer=b.id==='dex'?'Save the thanks for sunrise. We’re doing alright.':'You’re welcome. I’m staying on task.';}
 else if(/scared|afraid|creepy|bored/.test(s)){answer=`${this.night?'Keep your flashlight steady. Check the team list before following anyone.':'Daylight is our chance to explore. The chair assembly is strange even by this place’s standards.'} Want me to lead?`;}
 else{answer=`I can help with this expedition: say “follow me,” “find water,” “build here,” “help me,” or “find the chair room.” Right now I’m ${b.status.toLowerCase()} in ${sector(b.x,b.z)}.`;}
 this.say(b.name,answer);b.lastTalk=this.time;
 }
 }
 tick(dt){if(this.finished||!this.players.length)return;this.time+=dt;this.phaseTime+=dt;const duration=this.night?this.rules.night:this.rules.day;if(!this.night&&this.phaseTime>=duration-30&&!this.warned){this.warned=true;this.announce('30 SECONDS / LAST LIGHT','Get somewhere safe.');let b=this.bots.find(b=>!b.down);if(b)this.say(b.name,'Thirty seconds until lights out. Gather everyone; check your water.');}
 if(this.phaseTime>=duration){this.phaseTime-=duration;this.night=!this.night;this.warned=false;if(this.night){this.announce('NIGHT '+String(this.day).padStart(2,'0'),'The rooms are listening.');this.spawnNight();}else{this.day++;this.enemies=[];for(const i of this.pickups)i.active=true;for(const b of this.bots){if(b.down){b.down=false;b.hp=50;}b.inv.med=Math.max(1,b.inv.med);b.navAt=0;}this.announce('DAY '+String(this.day).padStart(2,'0'),'You are still here.');this.say('Radio','Daylight. Supplies have restocked. The next night will be harder.');}}
 for(const p of this.players){this.vitals(p,dt);let i=this.inputs.get(p.id);if(p.down||!i||this.time-i.at>.65){p.moving=false;continue}p.yaw=i.yaw;p.pitch=i.pitch;let mx=i.mx,mz=i.mz,len=Math.hypot(mx,mz);if(len>1){mx/=len;mz/=len}let sprint=i.sprint&&p.stamina>2&&len>.1;let speed=sprint?5.5:3.15;p.stamina=clamp(p.stamina+(sprint?-19:14)*dt,0,100);const sin=Math.sin(p.yaw),cos=Math.cos(p.yaw);let moved=this.world.move(p,(mx*cos+mz*sin)*speed*dt,(-mx*sin+mz*cos)*speed*dt,this.builds);p.moving=moved>.003;if(i.jump&&p.y<=.001&&p.stamina>10){p.vy=4.5;p.stamina-=10;i.jump=false}p.vy-=12*dt;p.y=Math.max(0,p.y+p.vy*dt);if(!p.y)p.vy=0;this.discover(p);}
 this.npcClock+=dt;for(const b of this.bots){this.vitals(b,dt);if(b.down)continue;if(this.time>b.planAt){this.planBot(b);b.planAt=this.time+.45+this.world.rand()*.2}this.walkNpc(b,dt,3.3,this.builds);}
 for(const e of this.enemies)this.enemy(e,dt);
 this.separateActors();
 if(this.night&&this.time-this.lastSpawn>24&&this.enemies.length<Math.min(14,5+this.day*2)){this.spawnEntity(this.day>1?'still':'stalker');this.lastSpawn=this.time}
 const allDown=this.players.every(p=>p.down);if(allDown&&(!this.bots.some(b=>!b.down)||this.players.every(p=>p.downTime>45))){this.finished=true;this.announce('TRANSMISSION LOST','The rooms remember.');}
 }
 separateActors(){const all=[...this.players,...this.bots,...this.enemies].filter(p=>!p.down);for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){let a=all[i],b=all[j],d=dist(a,b);if(d<.76){let dx=(a.x-b.x)/(d||1),dz=(a.z-b.z)/(d||1);if(d<.001){dx=1;dz=0}const amount=(.76-d)*.5;this.world.move(a,dx*amount,dz*amount,this.builds);this.world.move(b,-dx*amount,-dz*amount,this.builds)}}}
 vitals(p,dt){if(p.down){p.downTime+=dt;return}p.food=clamp(p.food-.095*dt*this.rules.drain,0,100);p.water=clamp(p.water-.14*dt*this.rules.drain,0,100);if(p.food<=0||p.water<=0)p.hp-=dt*1.2;if(p.food>70&&p.water>70&&this.time>p.hurtUntil+8)p.hp=Math.min(100,p.hp+dt*.28);if(p.bot){if(p.food<45&&p.inv.food){p.inv.food--;p.food=Math.min(100,p.food+44)}if(p.water<45&&p.inv.water){p.inv.water--;p.water=Math.min(100,p.water+44)}if(p.hp<35&&p.inv.med){p.inv.med--;p.hp+=45}}if(p.hp<=0){p.hp=0;p.down=true;p.downTime=0;p.moving=false;p.y=0;this.say(p.name,'I’m down! Get close and help me back up.');}}
 discover(p){let cx=clamp(Math.floor(p.x/10),0,12),cz=clamp(Math.floor(p.z/10),0,12),key=cz*13+cx;if(!this.visits.has(key)){this.visits.add(key);this.explored.push(key)}let r=roomAt(p.x,p.z);if(r&&r.id!=='arrival'&&!this.discoveries.includes(r.id)){this.discoveries.push(r.id);this.announce('NEW DISCOVERY / '+sector(p.x,p.z),r.name);let b=this.bots.find(b=>!b.down);if(b)this.say(b.name,{chairs:'All these chairs, and every one facing the same place. Check behind the last row.',pool:'The floor is flooded. The pillars are solid; the water is only shallow.',archive:'Records with no names. Search the shelves, and keep track of the exit.',garden:'Something green, finally. I still don’t trust the ceiling.',house:'Someone’s home. Except there’s no outside. Watch for copies.'}[r.id]);}}
 planBot(b){let p=this.players.find(p=>p.id===b.targetPlayer)||this.players[0];if(!p)return;b.goal=null;const dying=[...this.players,...this.bots].filter(p=>p.id!==b.id&&p.down).sort((a,c)=>dist(b,a)-dist(b,c))[0];if(dying){b.status='Rescuing';b.goal={x:dying.x,z:dying.z};if(dist(b,dying)<2.5){b.revive+=.5;if(b.revive>=2.5){this.revive(b,dying);b.revive=0}}return}b.revive=0;const threat=this.enemies.find(e=>dist(e,b)<5&&this.world.visible(e,b));if(threat){let d=Math.max(.1,dist(b,threat));b.goal=this.world.freeNear(b.x+(b.x-threat.x)/d*6,b.z+(b.z-threat.z)/d*6,2);b.status='Evading';if(this.time-b.lastTalk>25){this.say(b.name,'Entity close. Moving to cover.');b.lastTalk=this.time}return}
 if(dist(b,p)<2.8){let shared=false;for(const key of ['food','water'])if(b.inv[key]>1&&(p.inv[key]<2||p[key]<35)){b.inv[key]--;p.inv[key]=Math.min(99,p.inv[key]+1);if(p[key]<35&&p.inv[key]){p.inv[key]--;p[key]+=40}shared=true;}if((b.order==='help'||b.id==='sol')&&p.hp<65&&b.inv.med){b.inv.med--;p.hp=Math.min(100,p.hp+45);shared=true;}if(b.returning){b.returning=false;b.gatherCount=0;}if(shared&&this.time-b.lastTalk>8){this.say(b.name,'Shared supplies. Check your inventory.');b.lastTalk=this.time}}
 if(b.order==='wait'){b.status='Holding';b.goal=b.anchor;return}
 if(b.order==='build'){b.status='Building';if(b.inv.scrap<3){this.gather(b,p,'scrap');return}if(dist(b,b.anchor)>3){b.goal=b.anchor;return}let made=false;for(let k=0;k<12;k++){let a=k*Math.PI/6;const target={kind:b.buildCount>=3?'lamp':'wall',x:Math.round(b.anchor.x+Math.cos(a)*3),z:Math.round(b.anchor.z+Math.sin(a)*3),rot:Math.abs(Math.cos(a))>.7?Math.PI/2:0};if(this.canBuild(target)){this.place(target,b.id);b.inv.scrap-=target.kind==='wall'?3:2;b.buildCount++;made=true;break}}if(b.buildCount>=4||!made){b.order='follow';this.say(b.name,'Shelter placed. I left space to get out; entities can break through, so keep an escape route.');}return}
 if(b.order==='explore'){// goal is saved separately because each plan recomputes movement.
 b.goal=b.exploreGoal||b.savedGoal;if(!b.goal){b.order='follow';return}b.status='Leading';if(dist(b,b.goal)<3){this.discover(b);b.order='wait';b.anchor={...b.goal};this.say(b.name,'We’re here. I’ll hold this position while you look around.')}return}
 if(b.order==='gather'){if(b.returning){b.goal={x:p.x,z:p.z};b.status='Returning';return}this.gather(b,p,b.want);return}
 if(b.order==='help'){b.status='Assisting';b.goal=dist(b,p)>2?{x:p.x,z:p.z}:null;return}
 b.status='Following';if(dist(b,p)>3){const offset=this.bots.indexOf(b)*2.1;let target={x:p.x+Math.sin(p.yaw+offset)*2,z:p.z+Math.cos(p.yaw+offset)*2};if(this.world.blocked(target.x,target.z,.45,this.builds))target={x:p.x,z:p.z};b.goal=target}else if(!this.night){const near=this.pickups.find(i=>i.active&&dist(i,b)<2&&this.world.visible(b,i));if(near){near.active=false;b.inv[near.type]=Math.min(99,b.inv[near.type]+(near.type==='scrap'?3:1))}}
 }
 gather(b,p,want){b.status='Scavenging';const list=this.pickups.filter(i=>i.active&&(!want||i.type===want||(want==='water'&&i.type==='food'&&b.inv.water>4))).sort((a,c)=>dist(a,b)-dist(c,b));const target=list[0];if(!target){b.returning=true;b.goal={x:p.x,z:p.z};b.status='Returning';return}b.goal={x:target.x,z:target.z};if(dist(b,target)<1.8&&this.world.visible(b,target)){target.active=false;b.inv[target.type]=Math.min(99,b.inv[target.type]+(target.type==='scrap'?3:1));b.gatherCount=(b.gatherCount||0)+1;if(b.order==='build')return;if(b.gatherCount>=3){b.returning=true;this.say(b.name,'Found supplies. Bringing them back to you.')}}}
 walkNpc(p,dt,speed,builds){if(!p.goal||dist(p,p.goal)<.6){p.moving=false;return}if(this.time>p.navAt||!p.nav.length||dist(p.lastGoal||{x:-9,z:-9},p.goal)>3){p.nav=this.world.path(p,p.goal,builds);p.navAt=this.time+1.7;p.lastGoal={...p.goal}}let target=p.nav[0]||p.goal;if(dist(p,target)<.45){p.nav.shift();target=p.nav[0]||p.goal}let dx=target.x-p.x,dz=target.z-p.z,d=Math.hypot(dx,dz);if(d>.05){p.yaw=Math.atan2(-dx,-dz);const step=Math.min(speed*dt,d);let moved=this.world.move(p,dx/d*step,dz/d*step,builds,p.kind?.35:.34);p.moving=moved>.001;if(!p.moving)p.navAt=0}else p.moving=false;}
 spawnNight(){this.lastSpawn=this.time;this.enemies=[];const n=Math.min(11,3+this.day);for(let k=0;k<n;k++)this.spawnEntity(k===0?'still':k===1?'watcher':'stalker');}
 spawnEntity(kind){const p=this.players[Math.floor(this.world.rand()*this.players.length)];if(!p)return;let pos=this.world.freeNear(p.x+22,p.z+22,15);for(let k=0;k<40;k++){let a=this.world.rand()*Math.PI*2;let candidate=this.world.freeNear(p.x+Math.cos(a)*24,p.z+Math.sin(a)*24,3);if(dist(p,candidate)>15&&!this.world.visible(p,candidate)){pos=candidate;break}}const e={id:'e'+(++this.counter),kind,name:kind==='still'?p.name+'?':kind==='watcher'?'Watcher':'Stalker',color:kind==='still'?p.color:null,...pos,y:0,yaw:0,nav:[],navAt:0,goal:null,stun:0,attackAt:0,thinkAt:0,echoAt:this.time+9+this.world.rand()*18,moving:false};this.enemies.push(e);}
 enemy(e,dt){if(e.stun>this.time){e.moving=false;return}const targets=[...this.players,...this.bots].filter(p=>!p.down);if(!targets.length)return;let p=targets.sort((a,b)=>dist(e,a)-dist(e,b))[0];let d=dist(e,p);if(this.time>e.thinkAt){e.thinkAt=this.time+.65;if(d<35)e.goal={x:p.x,z:p.z};else if(!e.goal||dist(e,e.goal)<2)e.goal=this.world.freeNear(e.x,e.z,12)}let illuminated=targets.some(q=>q.flash&&dist(q,e)<15&&this.inFront(q,e,.78)&&this.world.visible(q,e));let speed=(e.kind==='stalker'?2.45:e.kind==='still'?2.15:1.9)*this.rules.speed*(1+Math.min(.35,(this.day-1)*.035));if(e.kind==='watcher'&&illuminated)speed*=.18;for(const b of this.builds)if(b.kind==='lamp'&&b.hp>0&&dist(b,e)<5)speed*=.75;this.walkNpc(e,dt,speed,this.builds);
 if(!e.moving&&e.goal){const barrier=this.builds.find(b=>b.kind==='wall'&&b.hp>0&&dist(e,b)<2.3);if(barrier)barrier.hp-=dt*(16+this.day*2)}if(d<1.2&&this.time>e.attackAt&&this.world.visible(e,p,this.builds)){e.attackAt=this.time+1.25;if(this.time>p.hurtUntil){p.hp=Math.max(0,p.hp-this.rules.damage);p.hurtUntil=this.time+.85;const f=Math.max(.1,d);this.world.move(p,(p.x-e.x)/f*.45,(p.z-e.z)/f*.45,this.builds);}}
 if(e.kind==='still'&&this.time>e.echoAt){e.echoAt=this.time+25+this.world.rand()*20;let copy=this.chatMemory[Math.floor(this.world.rand()*this.chatMemory.length)];this.say(copy?copy.name+'?':e.name,copy?copy.text:'I’m right here. Come back.',true)}
 }
 snapshot(){const clean=p=>{const {nav,goal,lastGoal,planAt,navAt,...rest}=p;return rest};return {seed:this.seed,difficulty:this.difficulty,time:this.time,phaseTime:this.phaseTime,day:this.day,night:this.night,rules:this.rules,players:this.players.map(clean),bots:this.bots.map(clean),enemies:this.enemies.map(clean),builds:this.builds.filter(b=>b.hp>0),pickups:this.pickups,messages:this.messages,events:this.events,explored:this.explored,discoveries:this.discoveries,finished:this.finished};}
}
