export const SIZE=13,CELL=10,EXTENT=SIZE*CELL;
export const ROOMS=[{id:'arrival',name:'THE ARRIVAL',x:5,z:5,w:3,h:3,color:0xb3ac74},{id:'chairs',name:'THE CHAIR ASSEMBLY',x:2,z:2,w:2,h:2,color:0xb5aca0},{id:'pool',name:'POOL ANNEX',x:9,z:2,w:2,h:2,color:0x79a7a2},{id:'archive',name:'RECORDS OFFICE',x:1,z:8,w:3,h:2,color:0x9c7165},{id:'garden',name:'THE CONSERVATORY',x:6,z:1,w:2,h:2,color:0x809476},{id:'house',name:'SOMEONE’S HOME',x:9,z:9,w:2,h:2,color:0xaa98a0}];
export const BOT_TYPES=[{id:'mira',name:'Mira',role:'Scout',desc:'Finds supplies. Knows the way.',color:0x87bdb2},{id:'dex',name:'Dex',role:'Builder',desc:'Builds shelter. Holds the line.',color:0xd3a262},{id:'sol',name:'Sol',role:'Medic',desc:'Shares supplies. Gets you up.',color:0xb2bde0}];
export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function rng(seed){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296}}
export function roomAt(x,z){return ROOMS.find(r=>x>=r.x*CELL&&x<(r.x+r.w)*CELL&&z>=r.z*CELL&&z<(r.z+r.h)*CELL)||null}
export function sector(x,z){return String.fromCharCode(65+clamp(Math.floor(x/CELL),0,12))+(clamp(Math.floor(z/CELL),0,12)+1)}
export class World{
 constructor(seed=91827){this.seed=seed;this.rand=rng(seed);this.walls=[];this.props=[];this.pickups=[];this.solids=[];this.hash=new Map();this.open=new Set();this.grid=Array.from({length:SIZE*SIZE},()=>({visited:false}));this.generate();this.navSize=EXTENT/2;this.nav=new Uint8Array(this.navSize**2);for(let z=0;z<this.navSize;z++)for(let x=0;x<this.navSize;x++)this.nav[z*this.navSize+x]=this.blocked(x*2+1,z*2+1,.45)?1:0;this.directions=[[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]];this.navLinks=new Uint8Array(this.nav.length);for(let z=0;z<this.navSize;z++)for(let x=0;x<this.navSize;x++){const i=z*this.navSize+x;if(this.nav[i])continue;this.directions.forEach(([dx,dz],k)=>{let xx=x+dx,zz=z+dz;if(xx<0||zz<0||xx>=this.navSize||zz>=this.navSize||this.nav[zz*this.navSize+xx])return;if(this.walkClear({x:x*2+1,z:z*2+1},{x:xx*2+1,z:zz*2+1}))this.navLinks[i]|=1<<k;});}}
 edge(a,b){return a<b?`${a}:${b}`:`${b}:${a}`}
 generate(){let stack=[84];this.grid[84].visited=true;while(stack.length){let a=stack[stack.length-1],x=a%SIZE,z=Math.floor(a/SIZE);const next=[[x+1,z],[x-1,z],[x,z+1],[x,z-1]].filter(([x,z])=>x>=0&&z>=0&&x<SIZE&&z<SIZE&&!this.grid[z*SIZE+x].visited);if(!next.length){stack.pop();continue}const [nx,nz]=next[Math.floor(this.rand()*next.length)],b=nz*SIZE+nx;this.open.add(this.edge(a,b));this.grid[b].visited=true;stack.push(b)}
 for(let z=0;z<SIZE;z++)for(let x=0;x<SIZE;x++){let a=z*SIZE+x;for(const [nx,nz] of [[x+1,z],[x,z+1]]){if(nx>=SIZE||nz>=SIZE)continue;const ra=roomAt(x*10+5,z*10+5),rb=roomAt(nx*10+5,nz*10+5);if((ra&&ra===rb)||this.rand()<.25)this.open.add(this.edge(a,nz*SIZE+nx));}}
 const addWall=(x,z,w,d)=>{let a={x,z,w,d,h:3.65};this.walls.push(a);this.addSolid(a)};
 addWall(0,65,.36,130);addWall(130,65,.36,130);addWall(65,0,130,.36);addWall(65,130,130,.36);
 for(let z=0;z<SIZE;z++)for(let x=0;x<SIZE;x++){let a=z*SIZE+x;if(x<12&&!this.open.has(this.edge(a,a+1)))addWall((x+1)*10,z*10+5,.3,10);if(z<12&&!this.open.has(this.edge(a,a+SIZE)))addWall(x*10+5,(z+1)*10,10,.3);}
 const prop=(type,x,z,rot=0)=>{let p={id:'p'+this.props.length,type,x,z,rot};const sizes={chair:[.7,.75,1.23],desk:[2,1,1.05],shelf:[2.2,.65,2.4],sofa:[2.7,1.05,1.2],plant:[.8,.8,1.9],crate:[1.1,1.1,1.1],pillar:[.65,.65,3.65],vending:[1.3,.85,2.45],bed:[1.8,2.4,.9],lamp:[.5,.5,1.9],cabinet:[1.2,.7,1.8]};let [w,d,h]=sizes[type];if(Math.abs(Math.sin(rot))>.7)[w,d]=[d,w];Object.assign(p,{w,d,h});this.props.push(p);this.addSolid(p);return p};
 for(let z=0;z<SIZE;z++)for(let x=0;x<SIZE;x++){let cx=x*10+5,cz=z*10+5,r=roomAt(cx,cz);if(r)continue;let v=this.rand();if(v<.18){prop('desk',cx-3,cz-2);prop('chair',cx-3,cz-.7)}else if(v<.4)prop('shelf',cx+3.5,cz,Math.PI/2);else if(v<.56)prop('sofa',cx,cz+3.5);else if(v<.68)prop('vending',cx-3.5,cz,Math.PI/2);else if(v<.84)prop('crate',cx-3,cz-3);else prop('plant',cx+3,cz-3);if(this.rand()<.23)prop('pillar',cx+2,cz+2);}
 // The arrival room is readable from spawn; supplies are directly ahead.
 for(const [x,z] of [[53,53],[77,53],[53,77],[77,77]])prop('pillar',x,z);
 prop('sofa',61,60);prop('desk',68,60);prop('chair',68,61.4);prop('vending',73,56);prop('shelf',57,57);prop('plant',55,62);prop('crate',62,69);prop('lamp',58.5,60);
 for(let z=23;z<39;z+=2.8)for(let x=23;x<39;x+=2.8){if(Math.abs(x-30)<1.8)continue;prop('chair',x,z,Math.PI)}
 for(let x=12;x<39;x+=4)for(let z=82;z<98;z+=6)prop('shelf',x,z,Math.PI/2);
 for(const [x,z] of [[64,14],[66,14],[72,14],[76,14],[64,25],[72,25],[77,25]])prop('plant',x,z);
 prop('sofa',95,95);prop('desk',95,97.5);prop('bed',104,104);prop('cabinet',107,97);prop('lamp',93,95);prop('chair',101,95);prop('plant',108,108);
 for(let z=22;z<40;z+=6)prop('pillar',99,z);
 for(let z=0;z<SIZE;z++)for(let x=0;x<SIZE;x++){let cx=x*10+5,cz=z*10+5;const count=roomAt(cx,cz)?.id==='arrival'?2:1;for(let k=0;k<count;k++){let px=cx+(this.rand()-.5)*5,pz=cz+(this.rand()-.5)*5;const types=['food','water','scrap','scrap','med'];if(!this.blocked(px,pz,.6))this.pickups.push({id:'i'+this.pickups.length,type:types[Math.floor(this.rand()*types.length)],x:px,z:pz,active:true});}}
 for(const [type,x,z] of [['food',64,62],['water',65,62],['scrap',66,62],['med',67,62]])this.pickups.push({id:'i'+this.pickups.length,type,x,z,active:true});
 }
 addSolid(a){this.solids.push(a);for(let z=Math.floor((a.z-a.d/2)/5);z<=Math.floor((a.z+a.d/2)/5);z++)for(let x=Math.floor((a.x-a.w/2)/5);x<=Math.floor((a.x+a.w/2)/5);x++){const key=x+':'+z;if(!this.hash.has(key))this.hash.set(key,[]);this.hash.get(key).push(a)}}
 nearby(x,z,r){const set=new Set();for(let zz=Math.floor((z-r)/5);zz<=Math.floor((z+r)/5);zz++)for(let xx=Math.floor((x-r)/5);xx<=Math.floor((x+r)/5);xx++)for(const a of this.hash.get(xx+':'+zz)||[])set.add(a);return set}
 overlap(x,z,r,a){const dx=Math.max(Math.abs(x-a.x)-a.w/2,0),dz=Math.max(Math.abs(z-a.z)-a.d/2,0);return dx*dx+dz*dz<r*r}
 blocked(x,z,r=.35,builds=[],height=0){if(x<.5||z<.5||x>EXTENT-.5||z>EXTENT-.5)return true;for(const a of this.nearby(x,z,r))if(a.h>height+.01&&this.overlap(x,z,r,a))return true;for(const a of builds)if(a.kind==='wall'&&a.hp>0&&a.h>height+.01&&this.overlap(x,z,r,a))return true;return false}
 move(p,dx,dz,builds=[],radius=.34){const n=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.18));let oldx=p.x,oldz=p.z;for(let i=0;i<n;i++){if(!this.blocked(p.x+dx/n,p.z,radius,builds,p.y||0))p.x+=dx/n;if(!this.blocked(p.x,p.z+dz/n,radius,builds,p.y||0))p.z+=dz/n}return Math.hypot(p.x-oldx,p.z-oldz)}
 visible(a,b,builds=[]){let len=dist(a,b);for(let t=.25;t<len;t+=.35){let f=t/len;if(this.blocked(a.x+(b.x-a.x)*f,a.z+(b.z-a.z)*f,.08,builds,1.45))return false}return true}
 freeNear(x,z,r=5){for(let k=0;k<60;k++){let a=this.rand()*Math.PI*2,d=this.rand()*r;let p={x:clamp(x+Math.cos(a)*d,1,129),z:clamp(z+Math.sin(a)*d,1,129)};if(!this.blocked(p.x,p.z,.5))return p}return {x:65,z:65}}
 walkClear(a,b,builds=[]){const d=dist(a,b),n=Math.max(1,Math.ceil(d/.35));for(let i=0;i<=n;i++)if(this.blocked(a.x+(b.x-a.x)*i/n,a.z+(b.z-a.z)*i/n,.4,builds))return false;return true;}
 path(a,b,builds=[]){const n=this.navSize,idx=(x,z)=>clamp(Math.floor(z/2),0,n-1)*n+clamp(Math.floor(x/2),0,n-1);let start=idx(a.x,a.z),end=idx(b.x,b.z);const pass=i=>!this.nav[i]&&!this.blocked(i%n*2+1,Math.floor(i/n)*2+1,.4,builds);let bestStart=Infinity,chosen=-1;for(let dz=-2;dz<=2;dz++)for(let dx=-2;dx<=2;dx++){let x=start%n+dx,z=Math.floor(start/n)+dz,i=z*n+x;if(x<0||z<0||x>=n||z>=n||!pass(i))continue;let q={x:x*2+1,z:z*2+1},d=dist(a,q);if(d<bestStart&&this.walkClear(a,q,builds)){bestStart=d;chosen=i;}}if(chosen<0)return [];start=chosen;if(!pass(end)){let best=1e9,found=-1;for(let dz=-3;dz<=3;dz++)for(let dx=-3;dx<=3;dx++){let x=end%n+dx,z=Math.floor(end/n)+dz,i=z*n+x;if(x<0||z<0||x>=n||z>=n||!pass(i))continue;let d=(x*2+1-b.x)**2+(z*2+1-b.z)**2;if(d<best){best=d;found=i}}if(found<0)return [];end=found}if(start===end)return [{x:b.x,z:b.z}];
 const g=new Float32Array(n*n).fill(Infinity),prev=new Int32Array(n*n).fill(-1),closed=new Uint8Array(n*n),heap=[];const heuristic=i=>Math.hypot(i%n-end%n,Math.floor(i/n)-Math.floor(end/n));const push=(i,f)=>{let k=heap.length;heap.push({i,f});while(k>0){let p=(k-1)>>1;if(heap[p].f<=f)break;[heap[p],heap[k]]=[heap[k],heap[p]];k=p}};const pop=()=>{let out=heap[0],last=heap.pop();if(heap.length){heap[0]=last;let k=0;while(true){let c=k*2+1;if(c>=heap.length)break;if(c+1<heap.length&&heap[c+1].f<heap[c].f)c++;if(heap[k].f<=heap[c].f)break;[heap[c],heap[k]]=[heap[k],heap[c]];k=c}}return out.i};g[start]=0;push(start,heuristic(start));let iterations=0;
 while(heap.length&&iterations++<5500){let u=pop();if(closed[u])continue;if(u===end){let path=[];while(u!==start&&u>=0){path.push({x:u%n*2+1,z:Math.floor(u/n)*2+1});u=prev[u]}path.push({x:start%n*2+1,z:Math.floor(start/n)*2+1});return path.reverse()}closed[u]=1;let x=u%n,z=Math.floor(u/n);for(let direction=0;direction<8;direction++){if(!(this.navLinks[u]&(1<<direction)))continue;let [dx,dz]=this.directions[direction];let xx=x+dx,zz=z+dz,v=zz*n+xx;if(xx<0||zz<0||xx>=n||zz>=n||closed[v]||!pass(v))continue;if(builds.length&&!this.walkClear({x:x*2+1,z:z*2+1},{x:xx*2+1,z:zz*2+1},builds))continue;let ng=g[u]+(dx&&dz?1.414:1);if(ng<g[v]){g[v]=ng;prev[v]=u;push(v,ng+heuristic(v))}}}return [];
 }
}
