import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import { chromium } from 'playwright';
const root=resolve(process.cwd());
const server=createServer(async(req,res)=>{try{let pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname.endsWith('/'))pathname+='index.html';let path=resolve(root,'.'+pathname);if(!path.startsWith(root+'/'))throw Error('outside root');let data=await readFile(path);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[extname(path)]||'application/octet-stream');res.end(data);}catch{res.statusCode=404;res.end('Not found');}});
await new Promise(r=>server.listen(4173,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1280,height:800}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(90000);
const checks=[];
try{
 await page.goto('http://127.0.0.1:4173/wildwake/?verify=1',{waitUntil:'networkidle'});
 await page.locator('#loading').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Run verification',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#verification-results').dataset.passed!==undefined,{},{timeout:180000});
 const simulation=JSON.parse(await page.locator('#verification-results').innerText());
 assert.equal(simulation.failed,0,JSON.stringify(simulation.checks.filter(c=>!c.passed)));
 assert.ok(simulation.passed>=82);checks.push('82 embedded simulation checks pass');
 await page.goto('http://127.0.0.1:4173/wildwake/',{waitUntil:'networkidle'});
 await page.locator('#loading').waitFor({state:'hidden'});
 await page.getByRole('button',{name:/Enter the wilderness/}).click();
 await page.locator('#hud').waitFor({state:'visible'});
 await page.locator('#pack-open').click();
 await page.getByRole('button',{name:'Crafting',exact:true}).click();
 assert.equal(await page.locator('[data-craft]').count(),18);checks.push('18 recipes are visible');
 await page.locator('[data-craft="spear"]').click();
 assert.match(await page.locator('#toast').innerText(),/Need/);checks.push('Missing materials give feedback');
 await page.getByRole('button',{name:'Map',exact:true}).click();
 assert.equal(await page.locator('.valley-map').count(),1);
 assert.match(await page.locator('#panel-content').innerText(),/Cedar Highlands/);
 await page.screenshot({path:'wildwake/tests/release-map.png'});checks.push('Expanded map and landmarks render');
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByLabel('Show touch controls').check();
 await page.getByLabel('Throw aim assistance').check();
 await page.getByRole('button',{name:'Close panel',exact:true}).click();
 assert.equal(await page.locator('#touch-climb').isVisible(),true);
 assert.equal(await page.locator('#touch-grab').isVisible(),true);
 await page.locator('#touch-climb').click();
 assert.match(await page.locator('#toast').innerText(),/tree|Climbing|Rest/);
 await page.locator('#touch-grab').click();checks.push('Touch climbing and grabbing controls respond');
 await page.locator('#quick-save').click();
 assert.match(await page.locator('#toast').innerText(),/saved/i);
 await page.locator('#pause-open').click();
 await page.locator('#load-pause').click();
 await page.locator('#hud').waitFor({state:'visible'});checks.push('Browser save and reload succeed');
 await page.screenshot({path:'wildwake/tests/release-game.png'});
 assert.deepEqual(errors,[]);
 const report={passed:true,simulation:{passed:simulation.passed,failed:simulation.failed},checks,errors};
 await writeFile('wildwake/tests/browser-release-results.json',JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
}finally{await browser.close();server.close();}
